### ISSUE TITLE
Multiple noop packets sent on upgrade

### ISSUE THREAD

**Issue by plievone** [socketio/engine.io#174]
Hi, it seems that a client can occasionally get dozens on noop packets from engine.io server during websocket upgrade, perhaps due to `checkIntervalTimer` in `lib/socket.js` triggering ten times per second, and not checking if it has succeeded in sending a noop packet already? Or is it intended to just keep sending until upgrade packet is received. The issue is seen mostly behind slow connections, of course.

**Comment by defunctzombie** [comment]
@plievone Is this still an open issue?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
