### ISSUE TITLE
remoteAddresse undefined when connecting from nodejs client (only on nodejs 0.10.x)

### ISSUE THREAD

**Issue by alaa-eddine** [socketio/engine.io#176]
when connecting to an engine.io server from engine.io-client on nodejs 0.10 , the client IP is undefined

to reproduce the behaviour here is a simple code

```
//server

var engine = require('engine.io')
  , http = require('http').createServer().listen(3000)
  , server = engine.attach(http)

server.on('connection', function (socket) {
   // reading client IP
    console.log('IP = ', socket.request.connection.remoteAddress);

    socket.on('message', function () { });
    socket.on('close', function () { });
});

```

```
//client
var socket = require('engine.io-client')('ws://localhost:3000/');
socket.onopen = function () {
    socket.onmessage = function (data) { };
    socket.onclose = function () { };
};
```

this code will give undefined addresse  on nodejs 0.10.x and the client IP on nodejs 0.8.x

what's strange is that when the client is a browser, the remoteAddress will be set on both nodejs 0.10.x and 0.8.x

(for browser test use the example on engine.io repository the above example will not open in browser) 

this behaviour depends on the server side nodejs version.
running the client with nodejs 0.10.x or 0.8.x don't change anything

**Comment by kaansoral** [comment]
I've created this feature request: #443

Really wish, after 3+ years, there would be an easy solution
