### ISSUE TITLE
socket.end() in handleUpgrade (server.js) cause "upstream prematurely closed connection while reading response header from upstream" in nginx

### ISSUE THREAD

**Issue by beatjoerg** [socketio/engine.io#283]
If there is an upgrade Request with an invalid sid the current implementation closes the connection immediatly. Which cause an error on nginx ("upstream prematurely closed connection while reading response header from upstream"). If I comment out the socket.end() it returns a 400 Header, which I expect. I have other failuers with the same error, but did not find yet the cause. 
Nginx Proxy Headers are set correctly.

```
Server.prototype.handleUpgrade = function(req, socket, upgradeHead){
  this.prepare(req);

  var self = this;
  this.verify(req, true, function(err, success) {
    //if (!success) {
    //  socket.end();
    //  return;
    //}

    var head = new Buffer(upgradeHead.length);
    upgradeHead.copy(head);
    upgradeHead = null;

    // delegate to ws
    self.ws.handleUpgrade(req, socket, head, function(conn){
      self.onWebSocket(req, conn);
    });
  });
};
```

**Comment by ookke** [comment]
I'm also seeing similar intermittent 502's with the same nginx log message with Nginx 1.5.1 so I guess this issue is still valid.

**Comment by beatjoerg** [comment]
Yes, we still see randomly 502, even with the patch above applied. 
I will look into this issue more deeply as soon as I can allocate a bit of time.

**Comment by andreassemborg** [comment]
I have the same problem.

**Comment by ryoqun** [comment]
Maybe we're affected this issue too.

**Comment by zcstarr** [comment]
I think I'm also encountering this just adding to this

**Comment by zcstarr** [comment]
Actually , I thought I had this issue earlier, then I put some debuggers in the Server code 
/socket.io/node_modules/engine.io/lib/server.js  specifically @ the server upgrade event handling, I realized that nginx was trying to upgrade an already upgraded web socket connection. There's no handler for that, so the solution in the Server.js code is to eventually time out and drop the socket connection , which triggered everyone's favorite 502, upstream prematurely closed connection while reading response header from upstream. Hope this helps !

**Comment by ryoqun** [comment]
@zcstarr Hmm, that's interesting info. Thanks for the tip!

**Comment by elgubenis** [comment]
i have that problem aswell, 1 machine using nginx to proxy 10 different node processes, now i want every node process to host a little socket.io server but i can only have 1 running at the same time.

**Comment by julianlam** [comment]
:+1: still happens from what we can tell

**Comment by julianlam** [comment]
@zcstarr If this is indeed the cause, then the underlying issue is that the client is trying to upgrade the connection twice, though I can't fathom a reason as to why that would happen.

If the connection is already upgraded, then the repeated call should also be answered with the expected `HTTP/1.1 101 Switching Protocols`, right?

**Comment by julianlam** [comment]
@rauchg Can we get this addressed please? The errors propagated up to nginx cause it to consider the app "down", when it isn't.

**Comment by darrachequesne** [comment]
@julianlam I didn't see any PR opened for that matter, did you find a solution?

**Comment by matikbird** [comment]
Any updates on this?

**Comment by julianlam** [comment]
:+1:

**Comment by meranamvarun** [comment]
I am still facing this issue
