### ISSUE TITLE
Transport is not closed when ping timeout

### ISSUE THREAD

**Issue by nkzawa** [socketio/engine.io#310]
reported from @ladymalie, thanks!

**Comment by nkzawa** [comment]
I noticed that this behavior would be intended to wait client timeout so that the closing reason becomes `ping timeout` on both side. But I heard this behavior causes a problem as follows.

> it mainly causes an issue on mobile safari (tested on v 7.2).
>
> given two tabs both running a websocket connection, when you open one of them, the other tab that is in the background will lose its connection server-side because it cannot receive a pong from the client. when you return the background tab in the foreground, the client waits for another ping interval before it closes.
>
> simply put, the timeout time is doubled in a sense.
>
> since the websocket is still open when the server times out, client-side is still trying to get a reaction from the server.

**Comment by darrachequesne** [comment]
Has this been fixed yet?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
