### ISSUE TITLE
Server#attach(server, options) should return Server:object

### ISSUE THREAD

**Issue by mhmeadows63** [socketio/engine.io#313]
According to the README.md, attach() should return the Server object.

**Comment by nkzawa** [comment]
This looks a bug of the doc since `attach()` doesn't create a new instance.

https://github.com/Automattic/engine.io#methods

**Comment by nkzawa** [comment]
Umm, actually the docs seems ok. `Server#attach` doesn't return a server instance, but `engine#attach` returns it.
