### ISSUE TITLE
TransportError

### ISSUE THREAD

**Issue by xZGit** [socketio/engine.io#321]
Error: parser decode error {type: "TransportError", description: Error: Invalid UTF-8 detected, stack: (...), message: "parser decode error"}
description: Error: Invalid UTF-8 detected
data: "42["user joined",{"user":{"name":"你好 你去哪儿"},"numUsers":2}]"
message: "Invalid UTF-8 detected"
stack: (...)
get stack: function () { [native code] }
set stack: function () { [native code] }
__proto__: d
message: "parser decode error"
stack: (...)
get stack: function () { [native code] }
set stack: function () { [native code] }
type: "TransportError"
__proto__: d

As about , when i use socket.io , I always get this error at engine.io version 1.5.1 , but if I use version 1.3.1 ，it works.  what is the  matter?

**Comment by nkzawa** [comment]
It seems your are using old version of engine.io-client. If so, please update it.
