### ISSUE TITLE
package.json different npm != git on version 1.5.1

### ISSUE THREAD

**Issue by martinoppitz** [socketio/engine.io#322]
Please increment.

**Comment by Karnith** [comment]
bump... except for engine.io, all of socket.io is failing compile on win 8.1. (engine.io-client, socket.io-client, socket.io)

**Comment by martinoppitz** [comment]
Yes. That is the problem. Ws 0.7.1 must be released in engine io....  Wait wait wait

**Comment by rajatksud** [comment]
BUMP .... On npmjs engine io is referring to previous version of ws 0.4.31 due to which it fails to compile. The version on git is correct.

**Comment by barryloper** [comment]
The NPM version 1.5.1 of engine.io-client requires ws@0.4.31, while engine.io requires 0.5.0. The older version of ws is failing to compile on my Ubuntu 15.04 x64 system. Any reason the client requires a different version? Can you just update the req. to at least 0.5.0?

**Comment by tian0cai** [comment]
I also encountered the same problem.
YEOMAN's almost never be used.

**Comment by nkzawa** [comment]
New versions have been released, thanks!
