### ISSUE TITLE
"request overlap" / "overlap from client"

### ISSUE THREAD

**Issue by contra** [socketio/engine.io#352]
https://github.com/socketio/engine.io/blob/1ecf02e32f05cf118f5506aaf704bb1059560836/lib/transports/polling.js#L76

Sockets that are in polling-mode disconnect after 60 seconds and this error is the cause - any ideas?

**Comment by contra** [comment]
I see this https://github.com/socketio/engine.io/issues/166 but it doesn't apply since there is no upgrade being attempted, the client is set to `transports: ['polling']`

**Comment by nkzawa** [comment]
I guess you use a non-js client? Let us know the details.

**Comment by contra** [comment]
Nope, js client (engine.io-client)

**Comment by nkzawa** [comment]
@contra how can we reproduce? Does this still occur on the latest version?

**Comment by contra** [comment]
I opened this issue last year so I don't remember the details - if it had been responded to I would have been able to provide more info. My solution was to quit using engine.io FWIW

**Comment by nkzawa** [comment]
So sorry for the delay. Anyway, closed for now. It could be reopened when we got reports from other people.

**Comment by aaaristo** [comment]
We are experiencing this as well and honestly i don't think this is a good solution:
https://github.com/socketio/engine.io/blob/1ecf02e32f05cf118f5506aaf704bb1059560836/lib/transports/polling.js#L76

What about mobile devices with any kind of retry mechanism embedded for any http request?
Or retries from a reverse proxy like AWS CloudFront: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-request-timeout

Couldn't we replace the current request with the last one? Thoughts?
