### ISSUE TITLE
Allow disabling deflate for ws

### ISSUE THREAD

**Issue by calzoneman** [socketio/engine.io#357]
Hello,

I noticed some performance issues on my socket.io server, and tracked it down to the fact that the `ws` module enables per-message zlib deflation by default.  This is nice if you're sending very large frames at a relatively slow rate, but for sending lots of very small messages it places unnecessary strain on the CPU and limits the number of frames socket.io can emit per second.

To benchmark this, I set up a socket.io server locally that just accepts messages from clients and broadcasts them.  I connected 100 clients and had each client send a message on a given interval.  Each message has a unique ID that the client uses to track the round trip time between sending the message and receiving it back.  I tuned the interval until I observed that the round trip time increases steadily, meaning that the socket.io server is backlogged and cannot recover until the message rate drops enough for it to drain.  I measured the number of "frames per second" (messages broadcast per second * number of clients) that socket.io was sending at this threshold.

On my desktop (i7-2600k @ 3.4GHz) using stock socket.io, I was able to reach about 8-9,000 frames/sec before socket.io became backlogged.  I then modified socket.io's engine.io dependency to pass `perMessageDeflate: false` to the `ws.Server` constructor, and observed that I was able to reach 50,000+ frames/sec-- a 5-6x increase in throughput.

It looks like @nkzawa added this option in a commit from January which has not landed in the release of engine.io: https://github.com/socketio/engine.io/commit/d11e17c8d7c09b9f0dbc4b0df72c6f6914aa68bc

Are there any plans to add this option any time soon?  For now I am manually patching engine.io on my servers since it is better for my application.

**Comment by Xaekai** [comment]
Yeah, this really damaged our users experience for an event we only do once a year. :disappointed:

**Comment by calzoneman** [comment]
Bump.

**Comment by calzoneman** [comment]
Any news on this?

**Comment by nkzawa** [comment]
Fixed in 1.6.x
