### ISSUE TITLE
iOS client

### ISSUE THREAD

**Issue by zhangxiaolian1991** [socketio/engine.io#358]
Is there any iOS client? My situation is that Server is engine.io(webSocket). I can not find any iOS client to use

**Comment by nkzawa** [comment]
There is no official iOS clienr for engine.io. But socket.io client for iOS exists https://github.com/socketio/socket.io-client-swift .

**Comment by Rajan** [comment]
@zhangxiaolian1991 Were you able to use socket.io swift client to connect with engine.io?
