### ISSUE TITLE
Why "Normalize" path?

### ISSUE THREAD

**Issue by JohnBaileyN** [socketio/engine.io#360]
Without getting into the details of my project's infrastructure, we have an issue with Engine.io's server.js _normalization_ of `path` option. 

What is really happening is that we are putting 

`
{path:  "/ws"}
`

However, due to the _normalizing_ of the path property, it ends up listening on `/ws/`

**Comment by nkzawa** [comment]
I think there is no reasonable reason here, guess it's just for make [path check](https://github.com/socketio/engine.io/blob/master/lib/server.js#L382) easy.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
