### ISSUE TITLE
Memory is not released in Ubuntu

### ISSUE THREAD

**Issue by Anson2048** [socketio/engine.io#361]
I have written a simple test。Are as follows

# server 

```coffee
'use strict'

http = require 'http'
engine = require 'engine.io'
logger = require('log4js').getLogger 'server ' + process.pid

showMem = ->
  mem = process.memoryUsage()

  for k, v of mem
    mem[k] = (v/1024/1024).toFixed(2)

  logger.info "mem: #{JSON.stringify(mem)}"

httpServer = http.createServer().listen 3000

engineServer = new engine.Server()

engineServer.attach httpServer

setInterval ->
  showMem()
, 1000 * 10

showMem()
engineServer.on 'connection', (socket) ->
  logger.info "clientCount: #{engineServer.clientsCount}"
  showMem()
  socket.on 'close', ->
    logger.info "clientCount: #{engineServer.clientsCount}"
    showMem()

```

# client

```coffee
'use strict'

async = require 'async'

clientsCount = 3000
limit = 10

sockets = []

options =
  transports: ['websocket']

pollingOptions =
  transports: ['polling']

async.timesLimit clientsCount, limit, (index, next) ->
  socket = require('engine.io-client')('ws://localhost:3000', pollingOptions)

  socket.on 'open', ->
    console.log 'open' + index
    sockets.push socket
    
    socket.on 'message', (data) ->
      console.log 'message', data

    next()
, (err) ->
  setTimeout ->
    socket.close() for socket in sockets
  , 1000
```
----
When a connection is disconnected memory will not be released,  but if manually invoke GC or in OSX doesn't have this problem. Had anyone encountered a similar problem.

**Comment by kapouer** [comment]
If is sufficient to test that memory is released when you call `global.gc()` (using --expose_gc flag).
If you don't want memory to grow too much, see https://github.com/nodejs/node/wiki/Frequently-Asked-Questions

**Comment by Anson2048** [comment]
@kapouer Thank you for your guidance. I set the --max_old_space_size=128. but dosn‘t work. I run command is coffee --nodejs  --max_old_space_size=128.

**Comment by kapouer** [comment]
max-old-spaces-size will trigger gc more often, but not necessarily just after a disconnection.
To know that you must call gc() explicitely after a disconnection. Then you can profile if memory is released (or not).
