### ISSUE TITLE
What time do you release a new version from master branch?

### ISSUE THREAD

**Issue by zensh** [socketio/engine.io#362]
I am waiting the new version.

**Comment by FoghostCn** [comment]
I am waiting too,custom socket id is useful for me,but I found it isn't in the new version

**Comment by zensh** [comment]
@rauchg Could you do me a favor?

**Comment by zensh** [comment]
Look for @rauchg

**Comment by rauchg** [comment]
Release coming asap!

**Comment by titoBouzout** [comment]
we just forgot to tell people room datatype changed :P "minor" change btw :P

**Comment by rauchg** [comment]
@titoBouzout 😩 we did mention it in the changelog, but we could have been more explicit about the specific datastructures involved. Apologies.
