### ISSUE TITLE
Upgrade to ws@1.0.0

### ISSUE THREAD

**Issue by Dignifiedquire** [socketio/engine.io#373]
Karma really needs this, as the current ws version is broken when used in combination with core-js. See https://github.com/karma-runner/karma/issues/1768#issuecomment-168114290 and https://github.com/websockets/ws/issues/645 for details on the bug and https://github.com/websockets/ws/releases/tag/1.0.0 for details on the release

**Comment by egoroof** [comment]
:+1:

**Comment by diwu1989** [comment]
really need a new release, thanks

**Comment by ef4** [comment]
Make that 1.0.1, there's a critical vulnerability in prior versions: https://nodesecurity.io/advisories/67
