### ISSUE TITLE
`closeTimeoutTimer` is not cleared when transport is upgraded

### ISSUE THREAD

**Issue by lpinca** [socketio/engine.io#376]
I noticed that the [`closeTimeoutTimer`](https://github.com/socketio/engine.io/blob/a31551e141d3ea227e3f85b93285007ca16e4de0/lib/transports/polling.js#L374) is not cleared when upgrading to websocket.
This leaves the timer running when there is no reason for it as the transport has been upgraded.

Maybe we can skip setting `shouldClose` and the `closeTimeoutTimer` when the polling transport is closed as a result of the websocket upgrade.

/cc @nkzawa

**Comment by nkzawa** [comment]
:+1: skipping `shouldClose` and `closeTimeoutTimer` sounds good to me.

**Comment by lpinca** [comment]
@nkzawa What would be in your opinion the best way to check if [`doClose`](https://github.com/socketio/engine.io/blob/a31551e141d3ea227e3f85b93285007ca16e4de0/lib/transports/polling.js#L356) has been called as a result of a transport upgrade?

I was thinking about adding an argument to [`clearTransport`](https://github.com/socketio/engine.io/blob/a31551e141d3ea227e3f85b93285007ca16e4de0/lib/socket.js#L199) like `fromUpgrade` and pass it all along till `doClose`:

- https://github.com/socketio/engine.io/blob/a31551e141d3ea227e3f85b93285007ca16e4de0/lib/socket.js#L276
- https://github.com/socketio/engine.io/blob/a31551e141d3ea227e3f85b93285007ca16e4de0/lib/transport.js#L59
- https://github.com/socketio/engine.io/blob/a31551e141d3ea227e3f85b93285007ca16e4de0/lib/transports/polling.js#L356

but there must be a cleaner way.

**Comment by nkzawa** [comment]
@lpinca That sounds good to me, I have no other good idea.

At first, I thought we might be able to do handshake when pausing transport, so that polling transport on server would get a pausing request and could be cleanly closed on both side. But this would cause to change the protocol and affect a lot.
