### ISSUE TITLE
ngrok postinstall error on npm install 

### ISSUE THREAD

**Issue by vicneanschi** [socketio/engine.io#379]
22936 verbose about to build C:\Users\VALVI\projects\github\socket.io\node_modul
es\istanbul
22937 info build C:\Users\VALVI\projects\github\socket.io\node_modules\istanbul
22938 info linkStuff istanbul@0.4.1
22939 silly linkStuff istanbul@0.4.1 has C:\Users\VALVI\projects\github\socket.i
o\node_modules as its parent node_modules
22940 verbose linkBins istanbul@0.4.1
22941 verbose link bins [ { istanbul: './lib/cli.js' },
22941 verbose link bins   'C:\\Users\\VALVI\\projects\\github\\socket.io\\node_m
odules\\.bin',
22941 verbose link bins   false ]
22942 verbose linkMans istanbul@0.4.1
22943 verbose rebuildBundles istanbul@0.4.1
22944 verbose rebuildBundles [ '.bin',
22944 verbose rebuildBundles   'abbrev',
22944 verbose rebuildBundles   'async',
22944 verbose rebuildBundles   'escodegen',
22944 verbose rebuildBundles   'esprima',
22944 verbose rebuildBundles   'fileset',
22944 verbose rebuildBundles   'handlebars',
22944 verbose rebuildBundles   'js-yaml',
22944 verbose rebuildBundles   'mkdirp',
22944 verbose rebuildBundles   'nopt',
22944 verbose rebuildBundles   'once',
22944 verbose rebuildBundles   'resolve',
22944 verbose rebuildBundles   'supports-color',
22944 verbose rebuildBundles   'which',
22944 verbose rebuildBundles   'wordwrap' ]
22945 info install istanbul@0.4.1
22946 info postinstall istanbul@0.4.1
22947 verbose unlock done using C:\Users\VALVI\AppData\Roaming\npm-cache\_locks\
istanbul-6ab0e3bc38209d8f.lock for C:\Users\VALVI\projects\github\socket.io\node
_modules\istanbul
22948 verbose stack Error: ngrok@0.2.2 postinstall: `node ./postinstall.js`
22948 verbose stack Exit status 1
22948 verbose stack     at EventEmitter.<anonymous> (C:\Users\VALVI\AppData\Roam
ing\nvm\v4.2.5\node_modules\npm\lib\utils\lifecycle.js:214:16)
22948 verbose stack     at emitTwo (events.js:87:13)
22948 verbose stack     at EventEmitter.emit (events.js:172:7)
22948 verbose stack     at ChildProcess.<anonymous> (C:\Users\VALVI\AppData\Roam
ing\nvm\v4.2.5\node_modules\npm\lib\utils\spawn.js:24:14)
22948 verbose stack     at emitTwo (events.js:87:13)
22948 verbose stack     at ChildProcess.emit (events.js:172:7)
22948 verbose stack     at maybeClose (internal/child_process.js:821:16)
22948 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_p
rocess.js:211:5)
22949 verbose pkgid ngrok@0.2.2
22950 verbose cwd C:\Users\VALVI\projects\github\socket.io
22951 error Windows_NT 6.1.7601
22952 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\bin\\npm-cli.js" "install"
22953 error node v4.2.5
22954 error npm  v2.14.12
22955 error code ELIFECYCLE
22956 error ngrok@0.2.2 postinstall: `node ./postinstall.js`
22956 error Exit status 1
22957 error Failed at the ngrok@0.2.2 postinstall script 'node ./postinstall.js'

**Comment by nkzawa** [comment]
Please describe the details. What versions of socket.io and node?

**Comment by vicneanschi** [comment]
I tried master branch of socket.io.
Versions (from log above)

22953 error node v4.2.5
22954 error npm v2.14.12

**Comment by nkzawa** [comment]
Thanks. It seems this is an error of `ngrok` module. Maybe the module doesn't work on Windows? I will report it to the `ngrok` author.

Anyway, I think you would be able to install `socket.io` by npm, since `ngrok` is a dev dependency.

**Comment by vicneanschi** [comment]
Ok. Thanks.
I wanted to run tests - so I need dev dependencies.

**Comment by darrachequesne** [comment]
Please re-open if needed. Thanks!
