### ISSUE TITLE
Replace ws with uws?

### ISSUE THREAD

**Issue by pesho** [socketio/engine.io#388]
https://github.com/alexhultman/uWebSockets

`uws` (`µWS`/`µWebSockets`) claims to be much more performant than `ws`:

* **23x** better short message throughput
* **21x** better connection performance
* **52x** less memory

Would be great to see this adopted in `engine.io`.

**Comment by kapouer** [comment]
The project is still missing SSL support and needs to be a little more mature to replace ws.
Eventually it would be a huge performance, memory usage, cpu load win !

**Comment by alexhultman** [comment]
@rauchg How would this happen in practice? I'm not very far from passing all tests and the only "porting" work required is to change `require('ws').Server` to `require('uws').Server`. Opt-in option for a test period?

**Comment by lpinca** [comment]
I don't think it is possible to switch to `uws` yet, one blocker for example is the lack of permessage-deflate support.

**Comment by lpinca** [comment]
Take a look at the [`websocket`](https://github.com/socketio/engine.io/blob/master/lib/transports/websocket.js) transport.

**Comment by kapouer** [comment]
@lpinca that's not a huge blocker, since it's probably not that hard to implement those flags again.
I believe engine.io could either accept an option to `require('thatwsclient')`. Let's PR that proposal :)

**Comment by kapouer** [comment]
See #390

**Comment by alexhultman** [comment]
All Engine.IO tests now pass with µWS as the ws implementation.

**Comment by rauchg** [comment]
This sounds amazing!

**Comment by rauchg** [comment]
I'll merge if you send a PR.

**Comment by rauchg** [comment]
> Node.js is broken on Windows and needs to be fixed for us to support the platform

Actually I can't :'(

**Comment by alexhultman** [comment]
Sarcasm?

**Comment by rauchg** [comment]
I just saw the PR to be able to opt-into it. Reviewing now.

**Comment by rauchg** [comment]
@alexhultman no sarcasm, I didn't realize #390 was a PR (thought it was an issue)

**Comment by alexhultman** [comment]
@rauchg Well in that case I must say I'm sorry for the harsh words. I'm not known for having the best patience. The option name is a little undecided IMO - it all depends on if the option is guaranteed to only apply to the server or not.

SocketCluster is going to name it's option wsEngine I think.

**Comment by alexhultman** [comment]
The goal in this would be to allow users of Socket.IO (and other projects) to easily swap to uws (or any other ws-implementation) without changing any of their code. something like this:

```javascript
var io = require('socket.io')(80, { wsEngine: 'uws' }); // wsModule, wsEngine, whatever cute name
```

This option should only apply to the server (µWS is only implementing the Server object of ws).

**Comment by kapouer** [comment]
It's `socket.io-client/node_modules/engine.io-client/node_modules/ws`
or `socket.io/node_modules/engine.io/node_modules/ws` so the wsEngine option is cute and explicit.

**Comment by pesho** [comment]
Resolved by #390, closing. Thanks @kapouer @alexhultman @rauchg!

**Comment by yinlubin1989** [comment]
厉害了 我哥

**Comment by yinlubin1989** [comment]
厉害了 我的哥 厉害我的 uws

**Comment by Bahramibh** [comment]
we can not use uws directly in nodejs application ?
