### ISSUE TITLE
engine.io-client 1.6.9 makes node.js socketio calls hang

### ISSUE THREAD

**Issue by ksylvan** [socketio/engine.io#396]
This is related to https://github.com/socketio/socket.io-client/issues/969

Again, not sure why the npm package is 1.6.9 while the source code here is only at version 1.6.8

I traced the problem down to the engine.io-client 1.6.9 update in the socket.io-client update.

After `npm install --save socket.io-client` I changed the `package.json` reference to be for `1.6.8`:

    /usr/src/app $ grep engine.io-client node_modules/socket.io-client/package.json 
    "engine.io-client": "1.6.8",

And now my tests work:

    $ ./test/run_tests InfoController
  
      InfoController
        /version:
      ✓ should return json (57ms)
      ✓ should have valid json info
      InfoController with sockets
        /version:
      ✓ should return data
      3 passing (16s)

Changing it back to 1.6.9, here is what happens:

    $ ./test/run_tests InfoController
  
     InfoController
        /version:
      ✓ should return json (41ms)
      ✓ should have valid json info 
      InfoController with sockets
        /version:
      1) should return data
      2 passing (12s)
      1 failing    
      1) InfoController with sockets /version: should return data:
         Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by kapouer** [comment]
It's not uncommon that upstream authors forget to `git push && git push --tags`.
For the problem you're seeing: is it that you have socket.io 1.6.8 on server, and socket.io-client 1.6.9 ?

**Comment by kapouer** [comment]
Are you using certificates ?

**Comment by ksylvan** [comment]
Yes I am using certificates.

I'm using sails.js on the server and mocha with socket.io-client for the unit tests.

**Comment by kapouer** [comment]
That's the only change between 1.6.8 and 1.6.9. The server version bump is a dull. The client changes only that behavior. It should have been a minor version bump at least...
Anyway, just set `opts.rejectUnauthorized = false;` and you're good to go !

**Comment by ksylvan** [comment]
I'm using the `sails.io.js` wrapper to connect to socket.io-client and engine.io. I don't see what the easy way is to set that option.

https://github.com/balderdashy/sails.io.js#for-nodejs

**Comment by kapouer** [comment]
Usually you can pass options, please see that with sails.io.js.

**Comment by ksylvan** [comment]
https://github.com/balderdashy/sails.io.js/pull/103 fixes the issue for me, along with setting the connection option before sails initiates the socket connection.

**Comment by darrachequesne** [comment]
Closing, as this is now fixed in sails.io.js.
