### ISSUE TITLE
using io.engine.clientsCount

### ISSUE THREAD

**Issue by Reeley** [socketio/engine.io#398]
So im using socket.io for a realtime chat. Today i decided to show how many users are currently connected. It works all fine, but when i refresh my page over and over very fast, the clientsCount rises above 1 client. Altough only one client is connected.

I also tried specify my own variable and incrementing it, when the connect event happens and decrement, when the disconnect event happens, yet the counter keeps rising.

**Comment by darrachequesne** [comment]
Hi! I could reproduce the clientsCount rising with only one client, yet the `pingTimeout` gets triggered after 60s and then the clientsCount decreases:

```
clientsCount++ > 1
clientsCount-- > 0
clientsCount++ > 1 // "slow" reload
clientsCount-- > 0
clientsCount++ > 1
clientsCount-- > 0
clientsCount++ > 1
clientsCount++ > 2
clientsCount++ > 3
clientsCount++ > 4
clientsCount++ > 5
// ~ 60s (only one browser opened)
clientsCount-- > 4
clientsCount-- > 3
clientsCount-- > 2
clientsCount-- > 1
// (closing browser)
clientsCount-- > 0
```

Do you confirm that behaviour?

**Comment by Reeley** [comment]
Yes i do! Thanks for the information :)
