### ISSUE TITLE
Next engine.io release?

### ISSUE THREAD

**Issue by yasserf** [socketio/engine.io#402]
Wondering when the next release is, as I'm keen to start using the uws integration that has been merged early last month.

**Comment by kapouer** [comment]
You can actually start using uws integration right now, please read [the UWS readme about socket.io](https://github.com/alexhultman/uWebSockets#socketio).

No reason to rush things ! i would find it a thousand times better if engine.io had an optional dependency on `uws` by default and kept a dependency on `ws`, and tried to load the uws module first and fallback to ws.
I think it's a little bit too soon to do that, though. The experience might be disappointing to the conservative user, but seeing how @alexhultman maintains uWebSocket, there is no doubt that in a few uws releases, engine.io should try using uws first in a default install.
Also i find it a little hypocrit to "leave the door open to other ws implementations" - there is little chance we see a lot of well-maintained websocket implementations... yes i mean that my PR #390 wasn't really a good idea.

**Comment by yasserf** [comment]
Thanks for the quick reply! I could see that I could override websocketServer with the uwS one. The only thing that's slightly annoying is that it would create a ws sever first and then I'll override it, but I'll certainly be able to work around that.


I think having an optional dependency makes alot more sense, for those where node-gyp isn't installed having uws not optional would result in a headache for some window users and node-gyp.
