### ISSUE TITLE
License of base64id

### ISSUE THREAD

**Issue by edi9999** [socketio/engine.io#403]
Hi,

the released version of the package `base64id` is "none", which can have some legal issues (code without license is considered as copyleft, eg you have no rights on it). The package maintainer doesn't seem to want/have time for updating the published package. (https://github.com/faeldt/base64id/issues/6)

Since they is a LICENSE in the git repository, we could simply copy the only file of this package inside engine.io 

This also has the benefit of being less dependent on other packages (events with kik , left-pad).

Would you accept a pull request that would take the one file of the base64id into the source code of engine.io ?

**Comment by kapouer** [comment]
The problem doesn't come from the package.json file itself: a missing license there has no legal implication. However, the published `base64id` npm package doesn't contain its LICENSE file - this is indeed an issue.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io/pull/451.
