### ISSUE TITLE
License of component-bind, object-component

### ISSUE THREAD

**Issue by edi9999** [socketio/engine.io#405]
Both component-bind and object-component are published without a LICENSE file on npm, which is pretty annoying.

https://github.com/component/bind/issues/12
https://www.npmjs.com/package/object-component

We should be fixing this.

**Comment by darrachequesne** [comment]
Update: both packages are not listed as dependencies anymore (as of `socket.io-client@3.0.5`):

- https://github.com/socketio/socket.io-client/commit/1fb1b78020dab80ea0a5147891a60b87e65d42f9
- https://github.com/socketio/socket.io-client/commit/7bc7a7b62464e12399fc5621fb88724988ad85ad
