### ISSUE TITLE
Make uws default engine

### ISSUE THREAD

**Issue by alexhultman** [socketio/engine.io#413]
@rauchg I think this is a sane thing to do now.
- npm install uws never fails (there are pre-compiled binaries for Windows, OS X and Linux).
- require('uws') can fail (it throws Error on failure such as compilation failed AND there is no pre-compiled binary available, or any other start-up errors).

By doing something like this:

``` javascript
var WebSocketServer;
try {
  WebSocketServer = require('uws');
} catch() {
  WebSocketServer = require('ws');
}
```

You can select implementation based on availability. Windows support is currently only working for Node.js 6.3.0, so it would be a good idea to always default to ws on Windows until patches to Node.js gets more widespread. I could make uws throw on Windows until I'm certain it works there.

uws (native server) is 34x faster than ws and 14x faster from Node.js + JavaScript. If you want Socket.IO to stay competitive I think this needs to be done sometime.

**Comment by kapouer** [comment]
That would be awesome, and it should have no impact on current user base.
