### ISSUE TITLE
Timeout 'til forever

### ISSUE THREAD

**Issue by omarojo** [socketio/engine.io#414]
Is there a way to make all clients try to reconnect forever ?

I have a server computer that shuts-down during the night. But clients that never shut-down, so when the server is down, all clients fail to connect. I need them to keep trying forever, until the server goes up again.

Any suggestions ?

**Comment by darrachequesne** [comment]
Hi! Sorry for the delay. Couldn't you use `socket.io-client`?

**Comment by darrachequesne** [comment]
Closed due to inactivity.
