### ISSUE TITLE
Cannot set Access-Control-Allow-Origin response header for XHR polling

### ISSUE THREAD

**Issue by pcolangelo73** [socketio/engine.io#430]
I am facing an issue when trying to set the `Access-Control-Allow-Origin` response header in socket IO when using xhr long polling. It seems that this library is hard coded to use either the value of the REQUEST header `origin`, or else `*`.

Looking at the code for `lib/transports/polling-xhr.js` in the `XHR.prototype.headers` method, it seems that we are unable to set this value from the server side:

The code in question: ( https://github.com/socketio/engine.io/blob/master/lib/transports/polling-xhr.js line 59):

```
// https://github.com/socketio/engine.io/blob/master/lib/transports/polling-xhr.js line 59
XHR.prototype.headers = function(req, headers){
  headers = headers || {};

  if (req.headers.origin) {
    headers['Access-Control-Allow-Credentials'] = 'true';
    headers['Access-Control-Allow-Origin'] = req.headers.origin;
  } else {
    headers['Access-Control-Allow-Origin'] = '*';
  }

  return Polling.prototype.headers.call(this, req, headers);
};
```

This seems strange to me as I would expect most people would want to set the header on the server side. Am I missing something here? Was this done for a reason or was this just an oversight?

**Comment by nkramaric** [comment]
I am also having this issue. Even if the request is coming from the same origin the header should be set. Any reason for explicitly setting it to '*'.

**Comment by darrachequesne** [comment]
I don't see any particular reason. PR is welcome!

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
