### ISSUE TITLE
Why wsEngine 'uws' didn't get released?

### ISSUE THREAD

**Issue by leonard-sxy** [socketio/engine.io#432]
Thanks for the great job.

I checked the source code a bit, then found:
```
var WebSocketServer = (this.wsEngine ? require(this.wsEngine) : require('ws')).Server;
```

So even in the option set the wsEngine as 'uws', will still use the ws engine, I am wondering why 'uws' engine didn't get released, are there some serious potential problems to use 'uws' engine?

**Comment by darrachequesne** [comment]
@leonard-sxy the option `wsEngine` should enable you to use the uws engine, doesn't it? Please note that you can also set the env variable `EIO_WS_ENGINE`.

**Comment by darrachequesne** [comment]
Please reopen if needed.

**Comment by kapouer** [comment]
Maybe now that uws@0.12.0 is so nice and stable, it should be listed as an optional dependency and be picked by engine.io, falling back to ws when uws fails to load ?

**Comment by darrachequesne** [comment]
@kapouer let's do that! could you please open a PR?
