### ISSUE TITLE
Packet parser 

### ISSUE THREAD

**Issue by QingYong** [socketio/engine.io#440]
Hi ,
  I got a data like this:
        42["action",{"action":"canEnterRoom","messageUUID":"18045"}]
when parsing with this function:
public static Packet<String> decodePacket(String data, boolean utf8decode) {
        int type;
        try {
            type = Character.getNumericValue(data.charAt(0));
        } catch (IndexOutOfBoundsException e) {
            type = -1;
        }

```
    if (utf8decode) {
        try {
            data = UTF8.decode(data);
        } catch (UTF8Exception e) {
            return err;
        }
    }

    if (type < 0 || type >= packetslist.size()) {
        return err;
    }

    if (data.length() > 1) {
        return new Packet<String>(packetslist.get(type), data.substring(1));
    } else {
        return new Packet<String>(packetslist.get(type));
    }
}
```

Result data is  2["action",{"action":"canEnterRoom","messageUUID":"18045"}]

what shoud I do to erase '2'

and what does 2 means?
Thanks.

**Comment by darrachequesne** [comment]
@QingYong where did you get the packet from? It seems that issue belongs to `engine.io-java`, doesn't it?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
