### ISSUE TITLE
Feature Request: Get a Client's *Current* IP

### ISSUE THREAD

**Issue by kaansoral** [socketio/engine.io#443]
### You want to:

* [] report a *bug*
* [x ] request a *feature*

### Current behaviour

In socket.io, both `socket.handshake.address` `socket.request.connection.remoteAddress` are initial IP's, when the IP of the client change, It's invisible to socket.io

### Steps to reproduce (if the current behaviour is a bug)

Connect to a server with one IP, dynamically switch to a network with a different IP, the connection is persisted, but the new IP isn't available

### Expected behaviour

There should be a clear and simple way for checking the current IP address of a connected user
There are 10's of questions and various answers that come short: https://www.google.com/search?q=socket+io+get+ip
I've inspected the entire socket object, yet couldn't find a reference to the current IP, all that's available is `.handshake.address`

**Comment by darrachequesne** [comment]
@kaansoral PR is welcome!

**Comment by kaansoral** [comment]
I added this `console.log(this.socket._socket.remoteAddress);` to engine.io/transports/websocket.js

And sadly the remoteAddress doesn't change there, the value is the initial value, so I can't think of a solution, without diving much deeper into the workings of the "ws"/websocket

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by kaansoral** [comment]
I would say it's needed, but don't know about the doability, I've tried achieving it for a long duration but seemed impossible at high level (diving into the ws library, maybe they didn't deem it important to keep track of the IP)

My solution was to have a separate HTTP periodic routine and an individual rotating key that each client needs to take from the socket, and periodically deliver via HTTP, where the IP is accessible

Otherwise, a player with a dynamic IP, could connect to the server 100's of times, and the server would think there are 100's of unique clients
