### ISSUE TITLE
Tests seem broken on build server

### ISSUE THREAD

**Issue by Matt90o** [socketio/engine.io#467]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
There seems to be a problem with testing new builds. When running 'npm test' on the build server, the following output is given: 
'Error: Cannot find module 'spdx-license-ids''

### Steps to reproduce (if the current behaviour is a bug)
Run 'npm test' to reproduce the issue.

### Expected behaviour
'npm test' should run all tests and exit normally. 

### Setup
- OS: 
- browser:
- engine.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
Check my pull request with a minor spelling mistake correction for an example.
https://travis-ci.org/socketio/engine.io/jobs/188468047

**Comment by darrachequesne** [comment]
I manually restarted the test, oddly it seems to pass now.

**Comment by darrachequesne** [comment]
Closing, as it seems the issue was related to npm.
