### ISSUE TITLE
Memory leak if trying to send data to closed Socket

### ISSUE THREAD

**Issue by konstantinzolotarev** [socketio/engine.io#468]
Here is check for only `closing` state. https://github.com/socketio/engine.io/blob/master/lib/socket.js#L382

But if `Socket` has `closed` readyState and somebody try to send something to this socket. Data remains in `this.writeBuffer` and eats memory. 

<img width="979" alt="screen shot 2017-01-04 at 8 02 16 pm" src="https://cloud.githubusercontent.com/assets/286431/21653234/c04a9eba-d2b8-11e6-8496-ead6e27f9fe0.png">

**Comment by darrachequesne** [comment]
Good catch! Would you mind opening a PR for that?

**Comment by konstantinzolotarev** [comment]
Yep will do tomorrow

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io/pull/469.
