### ISSUE TITLE
TypeError: Cannot read property 'displayName' of undefined at line https://github.com/socketio/engine.io/blob/1.8.2/lib/transports/websocket.js#L118

### ISSUE THREAD

**Issue by hansenyang** [socketio/engine.io#470]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

while client gets data from socket.io server, at code line of

https://github.com/socketio/engine.io/blob/1.8.2/lib/transports/websocket.js#L118

if err throws here, it would produce the error as below:
```
debug.js:195
  if (val instanceof Error) return val.stack || val.message;
                                      ^
TypeError: Cannot read property 'displayName' of undefined
```

and it could crash the KOA server

### Setup
- OS: Mac/Linux
- browser:
- engine.io version: 1.7.2

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

use `err` directly in stead of `err.stack`

**Comment by darrachequesne** [comment]
> https://github.com/socketio/engine.io/tree/1.8.2/lib/transports#L118

The line does not seem valid, could you please check?

**Comment by hansenyang** [comment]
https://github.com/socketio/engine.io/blob/1.8.2/lib/transports/websocket.js#L118

should be here, thank you

if there are data in buffer, they should be sent to client, I think

**Comment by darrachequesne** [comment]
Do you know where that `TypeError: Cannot read property 'displayName' of undefined` is thrown?

The `self.onError('write error', err.stack);` is used [here](https://github.com/socketio/engine.io/blob/1.8.2/lib/transport.js#L86):
```js
Transport.prototype.onError = function (msg, desc) {
  if (this.listeners('error').length) {
    var err = new Error(msg);
    err.type = 'TransportError';
    err.description = desc;
    this.emit('error', err);
  } else {
    debug('ignored transport error %s (%s)', msg, desc);
  }
};
```

**Comment by hansenyang** [comment]
Not sure where it throws, but at line https://github.com/socketio/engine.io/blob/1.8.2/lib/transports/websocket.js#L118
if update it with
```
self.onError('write error', err);
```
the crash is fixed

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
