### ISSUE TITLE
Cannot read property 'handleUpgrade' of undefined

### ISSUE THREAD

**Issue by lpinca** [socketio/engine.io#473]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

An error is thrown when not using `Server.prototype.attach` directly or indirectly.

### Steps to reproduce (if the current behaviour is a bug)

Run the following the test case

```js
'use strict';

const eioc = require('engine.io-client');
const eio = require('engine.io');
const http = require('http');

const server = http.createServer();
const engine = new eio.Server();

engine.on('connection', (socket) => {
  socket.on('message', (data) => socket.send(data));
  socket.on('close', () => console.log('close'));
});

server.on('upgrade', (req, socket, head) => {
  engine.handleUpgrade(req, socket, head);
});

server.on('request', (req, res) => {
  engine.handleRequest(req, res);
});

server.listen(3000, () => {
  const socket = eioc('http://localhost:3000');

  socket.on('open', () => socket.send('foo'));
  socket.on('message', (data) => console.log(data));
  socket.on('close', () => console.log('close'));
});

```

### Expected behaviour

The above example should work without throwing errors.

### Setup
- OS: macOS
- browser: -
- engine.io version: 2.0.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

```
TypeError: Cannot read property 'handleUpgrade' of undefined
    at /Users/luigi/eio-2.0/node_modules/engine.io/lib/server.js:360:12
    at Server.verify (/Users/luigi/eio-2.0/node_modules/engine.io/lib/server.js:171:3)
    at Server.handleUpgrade (/Users/luigi/eio-2.0/node_modules/engine.io/lib/server.js:349:8)
    at Server.server.on (/Users/luigi/eio-2.0/index.js:16:10)
    at emitThree (events.js:116:13)
    at Server.emit (events.js:194:7)
    at onParserExecuteCommon (_http_server.js:459:14)
    at onParserExecute (_http_server.js:418:3)
```

It seems that issue has been introduces in 7e50871c418a6fcffd211d72c3abe1a09035b52e as the [`init`](https://github.com/socketio/engine.io/commit/7e50871c418a6fcffd211d72c3abe1a09035b52e#diff-c945a46d13b34fcaff544d966cffcabaR103) method is only called when [`attach`](https://github.com/socketio/engine.io/commit/7e50871c418a6fcffd211d72c3abe1a09035b52e#diff-c945a46d13b34fcaff544d966cffcabaR441) is used.

**Comment by lpinca** [comment]
This prevents us from upgrading to `engine.io@2.0.0` in Primus.

cc: @kapouer

**Comment by lpinca** [comment]
The same issue also happens when using an already listening server:

```js
'use strict';

const eioc = require('engine.io-client');
const eio = require('engine.io');
const http = require('http');

const server = http.createServer();

server.listen(3000, () => {
  const engine = eio.attach(server);

  engine.on('connection', (socket) => {
    socket.on('message', (data) => socket.send(data));
    socket.on('close', () => console.log('close'));
  });

  const socket = eioc('http://localhost:3000');

  socket.on('open', () => socket.send('foo'));
  socket.on('message', (data) => console.log(data));
  socket.on('close', () => console.log('close'));
});
```

**Comment by exsilium** [comment]
HIt this myself, any suggestions for a fix?

**Comment by lpinca** [comment]
@exsilium https://github.com/socketio/engine.io/pull/459#issuecomment-274808715

**Comment by exsilium** [comment]
@lpinca Appreciated! :bowtie:

**Comment by exsilium** [comment]
I see... @lpinca , As i see #476 being open... I gather it will be eventually be pulled in for 2.0.1? Cheers!
