### ISSUE TITLE
Cannot send more than 16 MiB in a single message

### ISSUE THREAD

**Issue by lpinca** [socketio/engine.io#475]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

It is not possible to send more that 16 MiB of data in a single message

### Steps to reproduce (if the current behaviour is a bug)

Run the following test case

```js
'use strict';

const eioc = require('engine.io-client');
const eio = require('engine.io');
const http = require('http');

const server = http.createServer();
const engine = eio.attach(server, {
  maxHttpBufferSize: 20 * 1024 * 1024
});

engine.on('connection', (socket) => {
  socket.on('message', (data) => console.log(data.length));
});

server.listen(3000, () => {
  const socket = eioc('http://localhost:3000', {
    perMessageDeflate: false,
    transports: ['websocket']
  });

  socket.on('open', () => {
    socket.send('A'.repeat(17 * 1024 * 1024));
  });

  socket.on('close', () => console.log('close'));
});
```

### Expected behaviour

The `message` event should be emitted on the server and `17825792` logged on the console.

### Setup
- OS: macOS
- browser: -
- engine.io version: 2.0.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

The issue seems to be caused by `uws` which apparently ignores the `maxHttpBufferSize` option and hardcodes its value to 16 MiB. The above example works as expected with `engine.io@1.8.x`.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io/pull/501.
