### ISSUE TITLE
snyk reports vulnerabilites in ws version

### ISSUE THREAD

**Issue by nahammervold** [socketio/engine.io#478]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
https://snyk.io/vuln/npm:ws:20160920
✗ Medium severity vulnerability found on ws@1.1.1

### Steps to reproduce (if the current behaviour is a bug)
snyk test

### Expected behaviour
no vulnerabilites

### Setup
- OS: Windows
- browser: Chrome
- engine.io version:  engine.io@1.8.2 but uses the same ws version in master

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
socket.io also needs updating after this fix is implemented

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io/pull/480, thanks for the report.
