### ISSUE TITLE
dependency on "ws" version < 2.00 has security flaw in random number generator

### ISSUE THREAD

**Issue by paulrobello** [socketio/engine.io#479]
"ws" version < 2.00 has security flaw in random number generator

engine.io version 1.8.2
current dependency version "ws 1.1.1" 
needs to be "ws >= 2.0.0"

**Comment by ekryski** [comment]
I saw this as well. See here for more details. https://snyk.io/vuln/npm:ws:20160920

@darrachequesne @rauchg not sure what the implications are but it would probably be good to get a fix in soon. Let me know if/how I can help 😄

**Comment by NaLLiFFuNT** [comment]
I've faced this problem too.

**Comment by lpinca** [comment]
On the server this is not a issue as server to client frames are not masked, so it can be ignored here. On the client (engine.io-client) it may be an issue.

We have already backported the fix to the [`v1.x`](https://github.com/websockets/ws/commit/1653db1455805c1d253f489e3d4563ba3ffe821b) branch and we plan to release 1.1.2 soon.

I have no internet connection atm as my ISP decided to cancel my contract. I'm using my cell phone with only few MB of traffic left.

**Comment by darrachequesne** [comment]
@paulrobello I'll be happy to merge your pull request.

**Comment by paulrobello** [comment]
@darrachequesne Pull requests created for both server and client

**Comment by lpinca** [comment]
FYI we also release `ws@1.1.2` so you can use that if updating to version 2 is not possible due to the breaking changed.

**Comment by darrachequesne** [comment]
Released as `1.8.3` and `2.0.2`.

@lpinca thanks a lot!

**Comment by lpinca** [comment]
@darrachequesne you might want to tag version 2.0.2 as latest :)

```
npm dist-tag add engine.io@2.0.2 latest
```

currently the "latest" version is 1.8.3.

**Comment by darrachequesne** [comment]
Done, thanks! (again)
