### ISSUE TITLE
Don't intercept requests when the server doesn't listen

### ISSUE THREAD

**Issue by legikaloz** [socketio/engine.io#482]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:
Do not intercept and handle any http* request when the property `server.listening` is false.

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
I'm trying to close my server with `server.close(cb)`, but engine.io accept and handle incoming requests during server.close. This makes effectively impossible to safely stop and restart the server. 

### Steps to reproduce (if the current behaviour is a bug)
call `server.close(cb)` and try to connect to the engine.io endpoint from a client

### Expected behaviour
Do not intercept and handle any http* request when the property `server.listening` is false.

### Setup
- OS: Ubuntu 16.10
- node.js: 7.4.0
- engine.io version: 2.0.2

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
check server.listening in https://github.com/socketio/engine.io/blob/master/lib/server.js#L460:
`if (server.listening && check(req)) {`

**Comment by darrachequesne** [comment]
@legikaloz could you please open a pull request for that?

**Comment by darrachequesne** [comment]
`server.close` does close all clients, but it does not close the underlying http server. To properly stop it, you should use `engine.httpServer.close()`.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by legikaloz** [comment]
@darrachequesne you suggested to use `engine.httpServer.close()` but I can't find this method nor in the `ioServer` nor in the `io` variables. Have I missed something?

What I'm doing now:
```
var server = https.createServer(httpsOptions,app);
var ioServer = require('engine.io');
var io =ioServer.attach(server);
```
Attempt to close the connections:
```
    server.close(()=>{
        console.log('Server closed');
        setTimeout(()=>{
            console.log('Process exit now!');
            process.exit(1)
        },10000)
    });
```
With the call of `server.close()` the server stops accept **new** connections, **but existing connections  doesn't get closed when they're trying to reconnect**. This is the reason I proposed to check the `server.listening` property before intercept an incoming request. Without this extra check the server never gets closed, hence the callback never will be called.
