### ISSUE TITLE
update to uWebsocket 0.13

### ISSUE THREAD

**Issue by arden** [socketio/engine.io#483]
uWebsocket 0.13 has released, when engine.io update to uWebsocket 0.13?

**Comment by darrachequesne** [comment]
@arden could you please open a pull request for that? I didn't dig into the release log, any incompatible change?

**Comment by kapouer** [comment]
I'm currently using version 0.13.0 in production - it can replace version 0.12.0 as is.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io/pull/489.

@kapouer thanks for the details :+1:
