### ISSUE TITLE
Better debug/error information

### ISSUE THREAD

**Issue by konstantinzolotarev** [socketio/engine.io#488]
For now there is no good way to handle internal error messages + debugging this errors.

For example: 
We have CloudFlare -> Nginx -> Node.js (engine.io ws server) cluster
Pretty often I see such errors:
`*3712847 upstream prematurely closed connection while reading response header from upstream, client: 172.31.54.181, server: , request:`

But I couldn't debug this issue because If I'll enable `debug` for ws. It will flash me with tones of useless information.

As well on `Socket` close event I have only `forced close` message and have no idea why and where. `error` event is also not fired. 

`socket closed` and `transport closed` are also not very good info for searching an issue.

**Comment by darrachequesne** [comment]
Which version of engine.io are you using? Could this be related to https://github.com/socketio/engine.io/issues/283 (fixed in `1.8.2` by https://github.com/socketio/engine.io/pull/458)?

Regarding the debug message, you should be able to see the engine.io logs with `DEBUG=engine node index.js`, does it help? Else, do you know what we could improve here?

**Comment by konstantinzolotarev** [comment]
@darrachequesne I'll check version thank you.
Yep I know that I'm able to enable debug mode. but it gives totally useless messages. 
Another issue with it that when I'm enabling debug messages socket.io starts to print all messages it receive/send. It would be nice if there would be several log levels. 
Example: 
 - `level one` - received/sent messages
 - `level two` - transport close details (something more than `transport closed`)

Some more examples: 
https://github.com/socketio/engine.io/blob/master/lib/socket.js#L102 - here if socket receive pack with error - it might contain some useful information in packet. But message will be `parse error`. And developers will need to handle `packet` event, and recheck  `type == 'error'` in handler. 

https://github.com/socketio/engine.io/blob/master/lib/socket.js#L190
https://github.com/socketio/engine.io/blob/master/lib/socket.js#L217 - this 2 lines wouldn't provide any information about why transport closed. it means developer have to clone repo and patch it.

Same with `forced close` message. It sends from several different places. And you have to guess where system closed connection.

**Comment by darrachequesne** [comment]
@konstantinzolotarev could you please open a pull request with the change you're suggesting?

**Comment by konstantinzolotarev** [comment]
@darrachequesne I'll try. but not sure about available free time )

**Comment by konstantinzolotarev** [comment]
@darrachequesne I created an sample PR with idea. https://github.com/socketio/engine.io/pull/496

Pls take a look if you are ok with this approach I'll finish with other parts of the system

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
