### ISSUE TITLE
Pass the request IP address to allowRequest()

### ISSUE THREAD

**Issue by pensierinmusica** [socketio/engine.io#504]
Hi,

The `allowRequest` callback should have access to the IP address of the request (for example to allow only some IP addresses), but currently there doesn't seem to be any way to access it. Am I missing something?

@rauchg @darrachequesne 

Thanks!

**Comment by darrachequesne** [comment]
The first argument of `allowRequest` is an [IncomingMessage](https://nodejs.org/api/http.html#http_class_http_incomingmessage), so you should be able to get the IP address of the request with:

```js
function allowRequest(req, next) {
  let ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress;
}
```

**Comment by pensierinmusica** [comment]
Oops, dind't see it at first, awesome thx!!  :)
