### ISSUE TITLE
Access the socket id in the allowRequest() callback

### ISSUE THREAD

**Issue by pensierinmusica** [socketio/engine.io#505]
Hi,

In the `allowRequest` callback I'd need to have access to the id that gets assigned to the socket when I call `cb(null, true)`. Is there any way to do this?

@rauchg @darrachequesne 

Thanks!

**Comment by pensierinmusica** [comment]
Mmm.. I think I've figured out what the issue is, and created a pr for it  :)

**Comment by darrachequesne** [comment]
See https://github.com/socketio/engine.io/pull/506.
