### ISSUE TITLE
Issues with uws as default wsEngine on Debian

### ISSUE THREAD

**Issue by brenc** [socketio/engine.io#508]
### You want to:

* [x] report a *bug*

### Current behaviour
I tried to upgrade one of my apps to socket.io 2 (a simple chat app). Apparently uws will silently fail to compile, yet it still installs successfully. engine.io then silently switches to using ws (I have another ticket open about this). I would *never* have known that this happened had I not done a bunch of digging.

Turns out that uws doesn't support Wheezy and older LTS distros because [gcc 4.8 is required](https://github.com/uWebSockets/uWebSockets/issues/240). The uws owner also said [I expect the user to run pretty up-to-date systems (not debian)](https://github.com/uWebSockets/uWebSockets/issues/240). Unfortunately, there are many of us who can't up and switch distros overnight because of a requirement such as this.

uws DOES compile on Jessie (current stable) but it logs a bunch of warnings (which makes me nervous). I'd also be nervous about deploying on Debian at all at this point given the above statement.

### Steps to reproduce (if the current behaviour is a bug)
Install socket.io 2.x on Debian Wheezy or another LTS distro using gcc < 4.8. Look at `node_modules/uws/build_log.txt`.

### Expected behaviour
When I install socket/engine.io and *any* dependencies fail to compile, the entire install should fail. Both engines should NOT be installed at the same time and the engine should definitely NOT be silently switched to ws or anything else.

To me it makes the most sense to remove uws and ws as engine.io dependencies and let the user decide which engine to use explicitly. Installing both seems messy and confusing, especially when uws can silently fail to compile making it a gamble as to which engine is really being used.

### Setup
- OS: Debian Wheezy/Jessie x64, Node 6.x LTS
- engine.io version: 3.1.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I think making uws the default wsEngine was a bit hasty. This adds a whole new layer of complexity to an already very complicated system, especially for the newcomer. I'm fairly experienced with this stuff and I still had to mess around for hours with it before I finally gave up and reverted to socket.io 1.7.4 (I had other issues too).

I've stress tested ws and I'm fairly confident that it performs well enough for the _vast majority_ of users. uws still seems too bleeding edge and complex to be used as the default. It definitely seems like the option for more advanced users who know what they're doing and for people whose platform can support it.

**Comment by albertogasparin** [comment]
I also had issues with `uws` under Ubuntu 14.04.1 (4.2.0-27-generic x86_64). 
Somehow it was breaking requests to other resources (static files like js/css/images) closing the http connection unexpectedly and making the browser failing with `ERR_EMPTY_RESPONSE`.
Initially I thought that the problem was the middleware handling the static resources, but it turned out the connection was closed before the middleware even started streaming the resource to the client. I am instantiating socket.io as suggested:

```js
import http from 'http';
import socketIO from 'socket.io';

export default function(app) {
  app.server = http.createServer(app.callback());
  // override app.listen to start socket server too
  app.listen = (...args) => {
    app.server.listen.call(app.server, ...args);
    return app.server;
  };
  app.io = socketIO(app.server, { serveClient: false });
}
```

Changing `wsEngine` to `ws` magically fixes the issue, making requests no longer randomly failing 🤔
