### ISSUE TITLE
How to disable logging?

### ISSUE THREAD

**Issue by kc64** [socketio/engine.io#509]
When I run my socketio/engineio-based application with Flask, the run window floods with messages like this.  How can I disable them?

Thanks,
K

---

`INFO:engineio:4d4619dde53c46dabad4b96a3f7750db: Sending packet MESSAGE data 2["c...
INFO:engineio:4d4619dde53c46dabad4b96a3f7750db: Sending packet MESSAGE data 2["p...
INFO:engineio:4d4619dde53c46dabad4b96a3f7750db: Sending packet MESSAGE data 2["t...
INFO:engineio:4d4619dde53c46dabad4b96a3f7750db: Sending packet MESSAGE data 2["s...
INFO:engineio:4d4619dde53c46dabad4b96a3f7750db: Sending packet MESSAGE data 2["d...
INFO:engineio:4d4619dde53c46dabad4b96a3f7750db: Sending packet MESSAGE data 2["s...
INFO:engineio:4d4619dde53c46dabad4b96a3f7750db: Sending packet MESSAGE data 2["s...
INFO:engineio:4d4619dde53c46dabad4b96a3f7750db: Sending packet MESSAGE data 2["p...`

**Comment by tonysepia** [comment]
+1
