### ISSUE TITLE
engine.io package installation with yarn causes yarn.lock to not be created

### ISSUE THREAD

**Issue by jharris4** [socketio/engine.io#516]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
When installing engine.io 3.1.0 with yarn, the yarn.lock file is not created despite yarn saying it was.

### Steps to reproduce (if the current behaviour is a bug)

Create a package.json with the following content (only dependencies are important):

```
{
  "name": "yarn-lock-bug",
  "version": "1.0.0",
  "description": "repro bug with yarn not creating lock file",
  "author": "jharris4",
  "license": "MIT",
  "devDependencies": {
    "engine.io": "^3.1.0"
  }
}
```

then run `yarn install`

### Expected behaviour

yarn.lock file should be properly created. Yarn says it was, but the `yarn.lock` file does not actually exist.

### Setup
- OS: MacOS 10.12.5
- browser: N/A
- engine.io version: 3.1.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

This is consistently reproducible with Node 8.x, Yarn 0.24.6 and MacOS 10.12.5.

Note that the bug only reliably happens on first install (`rm -rf node_modules` and `rm yarn.lock`)

This bug was originally filed on yarn: https://github.com/yarnpkg/yarn/issues/3555

**Comment by jharris4** [comment]
This seems to be specific to the use of optionalDependencies section in package.json. I've filed a new issue in the yarn repro. https://github.com/yarnpkg/yarn/issues/3728

This issue can probably be closed, since it seems to be a bug in yarn. I only filed it here in case anyone else stumbles onto the same issue. :-)

**Comment by jharris4** [comment]
It's actually the `uws` package dependency that's causing the issue. I believe it may be because the package.json is missing `node-gyp` as a dependency. Created an issue/PR to fix it:

https://github.com/uNetworking/bindings/issues/31

**Comment by jharris4** [comment]
If/when that gets merged, I can confirm that it's fixed, and then it'd be great to update the `uws` version in `engine.io`'s dependencies...

**Comment by alexhultman** [comment]
uws is not deployed to or in any way supposed to work with Yarn. uws supports Node.js and NPM, nothing else. If you still insist on using it in environments where it is not intended to work then that's your issue.
