### ISSUE TITLE
Only websock transport can not work when client transports is ['polling', 'websocket']

### ISSUE THREAD

**Issue by SijieDingEsna** [socketio/engine.io#519]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*
When socket.io server side set transports : ['websocket'] and the client transports is ['polling', 'websocket'], socket.io always return unknown error in handshake process. 

### Expected behaviour
In handshake  process  the socket.io server should return upgrade response. After that polling request will be rejected. I have following reasons about this feature.

1. Some other client libraries such as python socketIO-client 0.7.2 depends on the handshake to determine use websocket. They don't allow use transport websocket directly.
2. Once server side support polling and websocket together, client side using the default setting ['polling', 'websocket'] of engine.io-client can still work.

### Setup
- OS:
- browser:
- engine.io version:

**Comment by darrachequesne** [comment]
@SijieDingEsna May I ask what your use-case is? Couldn't you simply specify `{ transports: ['websocket'] }` on the client?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
