### ISSUE TITLE
Server's .send() cannot send Buffer object

### ISSUE THREAD

**Issue by dennisat** [socketio/engine.io#520]
Hi guys, thanks for this awesome project, really nice work. 

I want to report a bug (probably) or a missing documentation... is not clear how to send and receive binary objects... or there is no need of documentation and this is simply a bug.

* [x] report a *bug*
* [ ] request a *feature*

### Current behavior
Although the client .send() is sending Buffer object and the server receives them, the server side cannot .send() Buffer objects. On .send(new Buffer(100)) there is no error or any exception.

### Steps to reproduce (if the current behavior is a bug)
Try to send a Buffer object from the server to client. ` .send(new Buffer(100))`

### Expected behavior
The client should receive something but nothing happened or an exception with a meaningful message.

### Setup
- OS: window
- browser: nodejs 7.2.0
- engine.io version: 2.0.3

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I haven't apply any special configuration like {binary: true} anywhere. No documentation on this topic :(.

**Comment by dennisat** [comment]
For client is described how apply the _binary mode_ here: https://github.com/socketio/engine.io-client#sending-and-receiving-binary
But for server where should we apply this?

**Comment by darrachequesne** [comment]
@dennisat you should be able to send a `Buffer` without any configuration:

```js
var engine = require('.');
var server = engine.listen(3000);

server.on('connection', function(socket){
  socket.send('utf 8 string');
  socket.send(new Buffer([0, 1, 2, 3, 4, 5])); // binary data
});

var socket = require('engine.io-client')('ws://localhost:3000');
socket.on('message', function(data){
  console.log(data);
  // prints:
  // utf 8 string
  // <Buffer 00 01 02 03 04 05>
});
```

**Comment by dennisat** [comment]
Thanks for the clarification!
