### ISSUE TITLE
Using internal, undocumented method `.listeners()` breaks non-core HTTP implementations

### ISSUE THREAD

**Issue by Qix-** [socketio/engine.io#525]
Engine.io seems to be using a non-standard, undocumented method called `listeners()` on `http.Server` objects (can be seen [here](https://github.com/socketio/engine.io/blob/master/lib/server.js#L456)).

Since this isn't a standard method, this breaks implementations of `http` that do not provide it (e.g. `mitol`).

Is there a way to remove the dependency on this method?

**Comment by lpinca** [comment]
It is a standard method as `http.Server` is an `EventEmitter`.
