### ISSUE TITLE
[Security] DOS vulnerability in requirement ws@2.3.1

### ISSUE THREAD

**Issue by jdforsythe** [socketio/engine.io#542]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Dependency on `ws` module with vulnerability

https://nodesecurity.io/advisories/550

### Setup
- OS:
- browser:
- engine.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Upgrade `ws` from 2.3.1 to >= 3.3.1

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io/pull/543. Thanks for the heads-up!
