### ISSUE TITLE
Using acknoledgment doesn't work with async code

### ISSUE THREAD

**Issue by Sharcoux** [socketio/engine.io#553]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [x] request a *feature*

### Current behaviour
emitting an event on the server, if the server makes asynchronous treatment before calling ack, null will be retrived to the client before the server could have a chance to response.

### Steps to reproduce (if the current behaviour is a bug)
client-side

     socket.emit('event', console.log)

server-side

     socket.on('event', callback => {
        new Promise(resolve => setTimeout(() => resolve('ok'), 1000)).then(callback);
    }

### Expected behaviour
Log "ok" client side

### Current result
Log "null" client side

### Setup
- OS: MacOs
- browser: Firefox
- engine.io version: 2.0.4

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I think that the issue is that socket.io probably send back "null" to the client if no listener used the acknoledgment function. I think that the best would be for socket.io to provide an option that would prevent this behaviour in exchange for ensuring that the server will provide an answer, or timeout.

**Comment by darrachequesne** [comment]
This seems to be fixed in latest versions (both in `socket.io@2` and `socket.io@3`). Please reopen if needed.
