### ISSUE TITLE
Send Additional Cookies in Handshake

### ISSUE THREAD

**Issue by jaykravetz** [socketio/engine.io#557]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Setup
- OS:
- browser:
- engine.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I would like to add a feature to allow additional cookies besides just `this.cookie || 'io'` to be set in the handshake.

I will have an example shortly.

### Edited
https://github.com/jaykravetz/engine.io/commit/3b629d293e6a9323c27e80998ad5e5cfffe25bb9

**Comment by jaykravetz** [comment]
https://github.com/jaykravetz/engine.io/commit/3b629d293e6a9323c27e80998ad5e5cfffe25bb9

**Comment by darrachequesne** [comment]
This was implemented in https://github.com/socketio/engine.io/commit/252754353a0e88eb036ebb3082e9d6a9a5f497db, and included in `engine.io@5.1.0`.

Syntax:

```js
server.on("initial_headers", (headers, req) => {
  headers["test"] = "123";
  headers["set-cookie"] = "mycookie=456";
});

server.on("headers", (headers, req) => {
  headers["test"] = "789";
});
```
