### ISSUE TITLE
Cannot use 'uws', because it's been abandoned

### ISSUE THREAD

**Issue by ghost** [socketio/engine.io#560]
* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

For Nodejs 8.x and 9.x (with uws = 8.x) works properly.

For Nodejs 10.x + uws (>= 8.x <= 9.x)： it throws an error saying "Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'".

For Nodejs 10.x + uws (>=10.x)：cannot find module 'uws'.

### Steps to reproduce (if the current behaviour is a bug)

Just assign 'uws' to `wsEngine`, each time I'll remove all the imports by directly removing node_modules and install them by running `npm i`. Then my `uws` is installed in the mode of dev-dependencies.

### Expected behaviour

Works properly like Node 8 or 9.

### Setup
- OS: Windows 8.1 (SP1), Linux (x64
- browser: N/A
- socket.io version: 2.0.4

### Other Info
I found `uws` is deprecated now, so in the main page of Socket.IO SHOULD'T SUPPORT THAT any more (See https://socket.io/docs/server-api/ part). And maybe there's something code to be changed with, or change to a new lib something like `uws`.

See the DUPLICATED `uws`: https://www.npmjs.com/package/uws, the version is changing TOO RAPIDLY, not so stable.

Maybe the logic as well as socketio should be modified？
(See codes at: https://github.com/socketio/engine.io/blob/6a16ea119280a02029618544d44eb515f7f2d076/lib/server.js#L107).

**Comment by Maledong** [comment]
In my test, it seems ONLY 10.148.0 works on me without any other configs, leave it here for others if they need help 

BTW：Will this be a hole in the future?!

**Comment by kkomelin** [comment]
Here is more info about what happened with uws https://www.reddit.com/r/node/comments/91kgte/uws_has_been_deprecated/

**Comment by Maledong** [comment]
Thanks @kkomelin

**Comment by slartibardfast** [comment]
hi, a fork / continuation is available, it even has a typescript based js component

https://www.npmjs.com/package/@clusterws/uws
https://github.com/ClusterWS/uWS

might be worth considering a switch?

**Comment by Maledong** [comment]
Thanks @slartibardfast

**Comment by Kamil93** [comment]
Does someone tested it with engine.io? https://www.npmjs.com/package/@clusterws/cws

**Comment by StefansArya** [comment]
Maybe `uws` was deprecated because [`uWebSockets.js`](https://github.com/uNetworking/uWebSockets.js) was released..

**Comment by DarkGhostHunter** [comment]
> Maybe `uws` was deprecated because [`uWebSockets.js`](https://github.com/uNetworking/uWebSockets.js) was released..

[No.](https://www.reddit.com/r/node/comments/91kgte/uws_has_been_deprecated/).

**Comment by StefansArya** [comment]
> [No.](https://www.reddit.com/r/node/comments/91kgte/uws_has_been_deprecated/).

Ok, I will change my comment..
Maybe we can use the official version of [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js) instead of the deprecated `uws` library..

**Comment by DarkGhostHunter** [comment]
We should use cWS instead of uWS. Who knows if the author gets another
tantrum and deletes the project itself.

**Comment by StefansArya** [comment]
Maybe you're right..
I haven't explore it much, so I will accept your suggestion.

**Comment by shirtleton** [comment]
uWS has not been abandoned. The maintainer created a new repo. https://github.com/uNetworking/uWebSockets.js

**Comment by stefanovualto** [comment]
> uWS has not been abandoned. The maintainer created a new repo. https://github.com/uNetworking/uWebSockets.js

Does that means that we can use `uWebSockets.js` as `wsEngine` into the server configuration?

**Comment by Kamil93** [comment]
@stefanovualto unfortunatelly not yet, uWebSocket.js has different structure.

**Comment by mmdevries** [comment]
@stefanovualto I'm not sure if this solves your issue but we have created a new package based on the original uws merged with some fixes from cws. The new package should be compatible with node 10 and 12.
https://github.com/mmdevries/uws

**Comment by stefanovualto** [comment]
@mmdevries I will give it a try thank you.

**Comment by mmdevries** [comment]
@stefanovualto, Great, please let me know your findings.

**Comment by marceloch2** [comment]
@stefanovualto Just installed your fork and seems fine but not fully tested across all our applications that consume our sockets.

There are any specific cases that i should look closer?

**Comment by stefanovualto** [comment]
@marceloch2 it is not my fork (I wish it was), but @mmdevries one.

**Comment by mmdevries** [comment]
@marceloch2, the "original uws" didn't work correct with node 10 and higher on secure connections. The SSL handshake was failing because Node 10 puts the SSL socket data into a SecureContext which could not be directly accessed. We added a workaround to overcome this issue.

When you use uws icw the Engine.IO layer compression was always disabled (at least in my opinion). We made a fix, now the flag indicating to compress the data coming from the Engine.IO is correcly send to the uws module. So, if you want yo have exactly the same behavior as before then you need to set the perMessageDeflate on false while initializing the engine.io layer.

**Comment by marceloch2** [comment]
@mmdevries Thanks for the explanation, it's so far running pretty fine with node -v 10.16.3.
If i find any issue i'll for sure share it here.

Thanks again for your time to upgrade this module.

**Comment by darrachequesne** [comment]
You can now use [eiows](https://www.npmjs.com/package/eiows), which is the published version of https://github.com/mmdevries/uws.

Again, a big thanks to @mmdevries :heart:
