### ISSUE TITLE
Official way for getting IP of socket

### ISSUE THREAD

**Issue by Kamil93** [socketio/engine.io#566]
There are Socket.io v2 and Engine.io v3 and (still O_O) there is not any official way for getting IP of connection. Why? It is one of the most needed feature.

**Comment by darrachequesne** [comment]
Hmm... it seems you are looking for `socket.handshake.address` ([ref](https://socket.io/docs/server-api/#socket-handshake)) :
```js
io.on('connection', (socket) => {
  let ip = socket.handshake.address;
  // ...
});
```

As usual, if you find ways to improve the documentation, please do open a PR! :+1:

**Comment by Kamil93** [comment]
I will, thanks for reply. The big problem is posts around the web about "this is a problem" and provided solutions that sometimes work, in some version of eio/sio work etc. so together with hole in documentation it makes me to post and issue here.

I've already found by consolelogging socket object that socket itself has remoteAddress property that contains correct (in my situation) IP, is it safe way? Or I should use socket.handshake.address?

**Comment by darrachequesne** [comment]
`socket.handshake.address` should actually be equal to the `remoteAddress` attribute:

- https://github.com/socketio/engine.io/blob/3.3.2/lib/socket.js#L37
- https://github.com/socketio/socket.io/blob/2.2.0/lib/socket.js#L124
