### ISSUE TITLE
cWS instead of uWS

### ISSUE THREAD

**Issue by Kamil93** [socketio/engine.io#567]
### You want to:

* [x] request a *feature*

### info

Does engine.io should support `cWS` instead of `uWS` websocket module?

`uWS` is dead and `cWS` is the most mature successor and uses `uWebsocket` under the hood too.

I've tried to implement it by myself in server.js of engine.io adding simply new case in switch statement:

```
switch (this.wsEngine) {
    case 'ws': wsModule = require('ws'); break;
    case 'uws': wsModule = require('uws'); break;
    case 'cws':
      wsModule = require('@clusterws/cws');
      wsModule.Server = wsModule.WebSocketServer;
    break;
    default: throw new Error('unknown wsEngine');
  }
```

It seems to not working at all, but it states compatibility with `ws` module.

cWS github project: https://github.com/ClusterWS/cWS

**Comment by darrachequesne** [comment]
Hi! I haven't had the time to check the `cws` module yet, but that looks promising. Are you able to connect with the client?

**Comment by Kamil93** [comment]
Unfortunatelly not, I've discovered that there are some incompatibilites with original ws module, like handleUpgrade has another arguments, 2 instead of 4, the main important one was callback param, I've done some changes to this method and it works but then another problem occured so I gave up for a while.

Wonder if it's even possible to support it in engine.io without big changes

**Comment by Kamil93** [comment]
@darrachequesne 

So far so good, I've upgraded "handleUpgrade" method to be compatible with ws module and also change default EventEmitter like here: https://github.com/ClusterWS/cWS#replace-eventemitter
to classic one from 'events' module and it works!

**Comment by yambakshi** [comment]
Whats the recommended uws workaround? Will it be removed from the wsEngine switch in server.js? (line 107)
It still throws an exception
Module not found: Error: Can't resolve 'uws'

**Comment by Kamil93** [comment]
@yambakshi, it is because you need to install uws first from npm (watch out for versions, read about uws author and why he had deleted it from npm)

**Comment by mmdevries** [comment]
@klimashkin, I'm not sure if this solves your issue but we have created a new package based on the original uws merged with some fixes from cws. The new package should be compatible with node 10 and 12.
https://github.com/mmdevries/uws

**Comment by darrachequesne** [comment]
Please take a look at [eiows](https://github.com/mmdevries/eiows), by @mmdevries.

Instructions here: https://socket.io/docs/server-installation/#Other-WebSocket-server-implementations
