### ISSUE TITLE
What should the default CORS behaviour be?

### ISSUE THREAD

**Issue by headlessme** [socketio/engine.io#570]
My cross origin requests are being blocked at the preflight stage by the following line. This check assumes that a handshake will only be GET requests:

https://github.com/socketio/engine.io/blob/cb0ac6fddcad12c454651bf0e1a312a154e228a4/lib/server.js#L166

This seems like it would break CORS requests from any modern browser? I know I can implement `handlePreflightRequest` to make this work, but not sure if that's the intended mechanism.

**Comment by headlessme** [comment]
Actually, looks like this line is why you have to implement `handlePreflightRequest`:

https://github.com/socketio/engine.io/blob/cb0ac6fddcad12c454651bf0e1a312a154e228a4/lib/server.js#L463

If you don't implement it then OPTIONS requests get pushed straight into the handleRequest flow for middleware without a fallback option.

**Comment by darrachequesne** [comment]
We're now relying on the [cors](https://www.npmjs.com/package/cors) module in order to handle all the configuration related to the CORS. The `handlePreflightRequest` was removed in Engine.IO v4.

```js
// before
new Server({
  handlePreflightRequest: (req, res) => {
    res.writeHead(200, {
      "Access-Control-Allow-Origin": 'https://example.com',
      "Access-Control-Allow-Methods": 'GET',
      "Access-Control-Allow-Headers": 'Authorization',
      "Access-Control-Allow-Credentials": true
    });
    res.end();
  }
});

// after
new Server({
  cors: {
    origin: "https://example.com",
    methods: ["GET"],
    allowedHeaders: ["Authorization"],
    credentials: true
  }
});
```
