### ISSUE TITLE
Error: Can't resolve 'uws'

### ISSUE THREAD

**Issue by evpozdniakov** [socketio/engine.io#575]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
I use socket.io, therefore engine.io is one of my depended packages.
When I try to bundle my project, I have error 
*Module not found: Error: Can't resolve 'uws' in node_modules/engine.io/lib/server.js*
(The error would not be here if I configure webpack with `webpack-node-externals`, but I really need all packages in a single bundle for docker container.)

### Steps to reproduce (if the current behaviour is a bug)
1. Add socket.io v2.2.0 to your existing project (which uses webpack) as a production dependency.
2. Require it in your entry point code.
3. Run webpack 

### Expected behaviour
It should create a bundle without errors.

### Setup
- OS: centOS
- browser: server side (node.js)
- engine.io version: 3.3.2

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
IMO it could be fixed if engine.io declares uws as a prod dependency (not a dev dependency).

**Comment by sethcwhiting** [comment]
This is discussed in an issue on the socket.io repo (https://github.com/socketio/socket.io/issues/3342), but I think it's more appropriate here. I found [codymikol](https://github.com/codymikol)'s answer very helpful:

> So I just had this same issue, but for a very different reason. Currently when I install the latest socket.io server package from npm uws will not be found.

>This is happening because the publisher of uws has recently uploaded an empty package deleting all of the actual code D:

>You can fix this by installing the last non destroyed release

>yarn add uws@10.148.1
>npm install uws@10.148.1

>Link to empty / deprecated package: https://www.npmjs.com/package/uws

>Insightful background info from reddit: >https://www.reddit.com/r/node/comments/91kgte/uws_has_been_deprecated/

>I'm going to post this in the top few results that come up when searching for this issue as it took me a while to figure out what was up and hopefully this will save someone out there some time!

**Comment by shirtleton** [comment]
[uWebSockets.js](https://github.com/uNetworking/uWebSockets.js) should be a drop in replacement for `uws`.

**Comment by mmdevries** [comment]
@sethcwhiting unfortunately this version doesn't work with node 10 and higher. At least if you want to use a secure connection(wss). We didn't want to step over to the javascript ws package and we created a new uws package and added support for node 10 and node 12.
This new package is based on the original uws and we merged some fixes from cws.
Maybe this will be useful for others as well.

https://github.com/mmdevries/uws

**Comment by TylerR909** [comment]
I'm running in to this same issue right now, trying to bundle server code up. Looks like `uws` is a devDependency despite having a `require('uws')` in the Server.init function. Thus it's not actually installed and webpack can't resolve it.

Thinking I can just define it as an empty module in Webpack considering I _don't_ toggle on the `uws` module but it's also hard to say considering engine.io is a 3rd-level-dependency (My dependency (1) depends on socket.io (2) depends on engine.io (3)).

**Comment by Femina** [comment]
Then what's the solution for this?

**Comment by goosewobbler** [comment]
@Femina installing the new uws package that @mmdevries mentioned seems to work for me so far...

**Comment by RossVertizan** [comment]
Is there a reason why uws can't be moved out of the devDependencies and into the dependencies alongside ws as @TylerR909 implied? 

I had the same problem with webpack and made a local edit to the package.json and now everything is OK.

**Comment by Domiii** [comment]
If you are here because your `webpack` build fails - good news: There is an easy fix!

## Problem Explanation

In recent `socket.io` versions, `ws` is already set as the default `wsEngine`. So unless you actually want to use `uws`, you don't have to worry about it at all because `engine.io` won't even `require` it in that case.

However, `webpack` does not know that. It only sees the dependency in the code, it sees `require('uws')`, and, not knowing that that part of the code will never execute, it will try to bundle it nevertheless.

## Solution

Simply tell it to not bundle it by adding `uws` to your [`externals`](https://webpack.js.org/configuration/externals/) in your `webpack.config` and you are done :)

E.g.:
```js
module.exports = {
  // ...
  externals: { 
     uws: 'uws' 
  }
};
```

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io/commit/85e544afd95a5890761a613263a5eba0c9a18a93, included in [engine.io@3.4.2](https://github.com/socketio/engine.io/releases/tag/3.4.2).
