### ISSUE TITLE
Question: new uWebsocket.js

### ISSUE THREAD

**Issue by Kamil93** [socketio/engine.io#578]
Is it possible without big changes to use new maintained uWebsocket.js (link below) for polling & websocket transports? I'd like to learn from engine.io code and start coding support for it.

Or should I start from null and create new lib.

https://github.com/uNetworking/uWebSockets.js

uWebsocket.js has support for websocket & http handling as well and is much faster and lighter than ws and I guess has same speed as uws (same author) or even faster because of live maintaining

**Comment by shirtleton** [comment]
Thanks for bringing this up again @Kamil93.
This has been a topic of debate for a few months now with little to no movement on the issue.

https://github.com/socketio/engine.io/issues/560

**Comment by Kamil93** [comment]
I guess if we don't want a lot of changes in eio, it's necessary to create wrappers:

- class that emulate ws.Server class
- wrapper for request object, because req from uws.js has short lifetime (only while executing callbacks) and eio stores sometimes request for later. Differences in methods&getters names are also the reasons.

**Comment by darrachequesne** [comment]
You can also take a look at [eiows](https://github.com/mmdevries/eiows), which is a fork of the `uws` package.

Instructions here: https://socket.io/docs/server-installation/#Other-WebSocket-server-implementations

**Comment by darrachequesne** [comment]
Added in `engine.io@6.1.0`:

```js
const { App } = require("uWebSockets.js");
const { uServer } = require("engine.io");

const app = new App();
const server = new uServer();

server.attach(app);

app.listen(3000);
```

I plan to merge the changes in Socket.IO, so we can benefit from the [publish](https://unetworking.github.io/uWebSockets.js/generated/interfaces/TemplatedApp.html#publish) functionality.

Feedback is welcome!
