### ISSUE TITLE
Creating multiple instances of WS server

### ISSUE THREAD

**Issue by alesmenzelsocialbakers** [socketio/engine.io#579]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

WS instance is created per init() call. One is called in the constructor and then it is overriden in attach function, this means any event handlers on the previous instance wont be called.
PS: I am trying to attach io.engine.ws.on('headers', (headers, req) => ... ) so i can fix the security headers.

Creating first instance - https://github.com/socketio/engine.io/blob/master/lib/server.js#L65
Override - https://github.com/socketio/engine.io/blob/master/lib/server.js#L457

### Expected behaviour

Single instance of the WS server is created

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
