### ISSUE TITLE
Please publish latest changes and integrate into socket.io

### ISSUE THREAD

**Issue by oliversalzburg** [socketio/engine.io#588]
### You want to:
* [] report a *bug*
* [x] request a *feature*

### Current behaviour
Whenever socket.io is loaded, NodeJS displays a warning about a deprecated `Buffer` usage in engine.io → base64id.

### Steps to reproduce (if the current behaviour is a bug)
`require( "socket.io" )`

### Expected behaviour
No deprecation warnings are emitted.

### Setup
- OS: Windows
- browser: -
- engine.io version: 3.3.2

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
The deprecated code in base64id was fixed and published in 2.0.0. The change has been integrated into engine.io, which already points to the new dependency version at HEAD, but the change has not yet been published and integrated into upstream packages, which still causes the deprecation to be emitted.

**Comment by darrachequesne** [comment]
Released as 3.4.0 => https://github.com/socketio/engine.io/releases/tag/3.4.0

Sorry for the delay!

**Comment by oliversalzburg** [comment]
Can you include this new version in socket.io? The current dependency semver range won't catch it.
