### ISSUE TITLE
debug dependency

### ISSUE THREAD

**Issue by simllll** [socketio/engine.io#591]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
"debug" package is a "dependency", and not a dev or peer dependency. Debug package itself is not working in internet explorer though.
Is this intended? Debug sounds very much to me as "debug", not as depedency?

### Expected behaviour
use debug only in dev depedency, make includes optoional.

**Comment by deser** [comment]
Also it doesn't work with uglify due to `const` in production code

**Comment by darrachequesne** [comment]
Yes, it's intended. It allows users to print information about what's happening. More information here: https://socket.io/docs/logging-and-debugging/

> Debug package itself is not working in internet explorer though.

You should be able to remove it from the browser bundle, like we do [here](https://github.com/socketio/socket.io-client/blob/661f1e7fac2488b6d3d206f96bb59073c4c98b1c/support/webpack.config.slim.dev.js#L30). You can also take a look at [webpack-remove-debug](https://github.com/johngodley/webpack-remove-debug).

I've edited the documentation [here](https://socket.io/docs/logging-and-debugging/#Removing-debug-from-your-browser-bundle).
