### ISSUE TITLE
SameSite cannot be set to None

### ISSUE THREAD

**Issue by daveisfera** [socketio/engine.io#603]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
`SameSite` is set on the cookie with 2.3.0 which prevents use with iframes and such

### Steps to reproduce (if the current behaviour is a bug)
Run with `cookie` to `true` or a `string` and observe the cookie is created with `SameSite=Strict`

### Expected behaviour
`SameSite` can be set to `None` with `Secure` so that it can meet [current browser expectations](https://web.dev/samesite-cookies-explained/#changes-to-the-default-behavior-without-samesite)

### Setup
- OS: macOS 10.15.6
- browser: Chrome 84.0.4147.105
- engine.io version: 3.4.2

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I'll submit a PR

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io/commit/19cc58264a06dca47ed401fbaca32dcdb80a903b (included in `engine.io@3.5.0`).
