### ISSUE TITLE
On Webpack and CRA build there is an WARN "Critical dependency: the request of a dependency is an expression"

### ISSUE THREAD

**Issue by dennisat** [socketio/engine.io#609]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a _sort of_ *bug*
* [ ] request a *feature*

### Current behaviour
When the webpack is trying to put the engine.io in a bundle, we get an optimization warning due to an expression in require() of the engine.io library.

Webpack tries to resolve required calls statically to make a minimal bundle. 
Your library in node_modules/engine.io/lib/server.js file and at line 80 it doing this:
```
this.opts.wsEngine === "ws" ? require("ws") : require(this.opts.wsEngine);
```
The last require() has an expression as argument.

Can we rid of this warn?

### Steps to reproduce (if the current behaviour is a bug)
- Add the engine.io into a project with a webpack builder.
- Build the app to make a bundle that has the engine.io.

### Expected behaviour
- No Webpack warning: "Critical dependency: the request of a dependency is an expression"

### Setup
- OS: macOs
- browser: node v12.19
- engine.io version: 4.0.1

## The warning:

```
WARNING in ./node_modules/engine.io/lib/server.js 74:67-94
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/engine.io/lib/engine.io.js
 @ ... the node app ...
```

**Comment by darrachequesne** [comment]
@dennisat do you have a suggestion on how to write this? We need to be able to load any WebSocket library that exposes an interface compatible with the `ws` module. (like `uws` or `eiows`)

Should we list all possible options? (but in that case they will all be included in the webpack bundle, won't they?)

**Comment by dennisat** [comment]
Yeah, I got your point.

I think the cleanest solution is to ask the reference of the `ws module` instead of the name (string) of it. 

So we can have something like this.

```
const superWs = require('super-ws');
const engine = require('engine.io');

const server = new engine.Server({wsEngine: superWs});
```

This way will be safer for the developer since will not be possible to define a `wsEngine` that is not loaded in the bundle.

**Comment by darrachequesne** [comment]
That makes sense :+1: let's schedule this for v5 then.

**Comment by Korijn** [comment]
Is there a work around for this? It's incredibly annoying.

**Comment by kerry-Cho** [comment]
@darrachequesne Has this problem been solved? 
I have the same problem when building webpack.

**Comment by darrachequesne** [comment]
@kerry-Cho no, this is not resolved yet. Please note that this is only a warning, everything should work as expected.

**Comment by Korijn** [comment]
We're holding off on upgrading until it's fixed, since.. well.. warnings technically aren't a problem for the build or the functionality of the system, but they cause coworkers to ask questions. :)

**Comment by kerry-Cho** [comment]
@darrachequesne  thanks a lot , I look forward to fix that.

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/engine.io/commit/edb734316f143bf0f1bbc344e966d18e2676b934 and included in [`engine.io@5.0.0`](https://github.com/socketio/engine.io/releases/tag/5.0.0).
