### ISSUE TITLE
Request backport #550 to v3.1.x branch

### ISSUE THREAD

**Issue by nekolab** [socketio/engine.io#615]
Hi

We've experienced some wired issue on v3.1.5, after check we found it's caused by package `uws` during package installing stage

For some reason, we were stuck on v3.1.x branch. Since #550 seems not a breaking change, I'm here to ask if it is possible to backport it to v3.1.x branch

Thanks in advance

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
