### ISSUE TITLE
Ability to have Strict-Transport-Security header

### ISSUE THREAD

**Issue by tonyxferall** [socketio/engine.io#620]
**Is your feature request related to a problem? Please describe.**
HTTP headers are limited

**Describe the solution you'd like**
Would be nice to be able to add headers, particularly a Strict-Transport-Security header

**Describe alternatives you've considered**
forking/patching with a hard-coded Strict-Transport-Security header

**Additional context**
Some pentesters will catch/ding missing Strict-Transport-Security header

**Comment by darrachequesne** [comment]
You can use the `headers` event, which was added in `engine.io@5.1.0`:

```js
server.on("headers", (headers) => {
  headers["Strict-Transport-Security"] = "...";
});
```

**Comment by tonyxferall** [comment]
Thanks!
