### ISSUE TITLE
Moderate        Regular expression denial of service

### ISSUE THREAD

**Issue by Muskan-Jaiswal** [socketio/engine.io#625]
Moderate        Regular expression denial of service                          

  Package         glob-parent                                                   

  Patched in      >=5.1.2                                                       

  Dependency of   @angular-devkit/build-angular [dev]                           

  Path            @angular-devkit/build-angular > webpack-dev-server >          
                  chokidar > glob-parent                                        

  More info       https://npmjs.com/advisories/1751                             

found 1 moderate severity vulnerability in 1318 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by darrachequesne** [comment]
Hi, thanks for the report.

`glob-parent` is not in the dependency tree though:

```
$ npm ls  glob-parent
engine.io@5.1.1 .../engine.io
└── (empty)
```

Could you please check where the vulnerability is reported?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
