### ISSUE TITLE
this.pingIntervalTimer.refresh is not a function

### ISSUE THREAD

**Issue by JeffWinder** [socketio/engine.io#631]
**Describe the bug**
socket.js:108 Uncaught TypeError: this.pingIntervalTimer.refresh is not a function
    at Socket.onPacket (socket.js:108)

**To Reproduce**
engine.io: 6.1.0
engine.io-client: 6.1.1
socket.io: 4.4.0
socket.io-client: 4.4.0

**Platform:**
 - OS: windows 10

**Additional context**
Adding
`console.log(typeof  this.pingIntervalTimer)` 
just before line 108 shows that it's a number, not a Timer.

`this.pingIntervalTime.refresh()` 
was added here it seems:
https://github.com/socketio/engine.io/commit/37474c7e67be7c5f25f9ca2d4ea99f3a256bd2de

**Comment by darrachequesne** [comment]
Which version of Node.js are you using? The `refresh` method was added in v10.2.0.

**Comment by JeffWinder** [comment]
Yes I saw that: https://nodejs.org/api/timers.html#timeoutrefresh
I've tried with 16.9.1, 16.11.1 and 16.13.0
I'm using socket.io in Electron v16.0.2

**Comment by JeffWinder** [comment]
And now I'm suddenly getting the type of `Timer `back instead of  `number`, for all three node versions mentioned above, no idea what changed on my end. As if it was seen as the javascript`setTimout `  before. So now the error is gone.

**Comment by JeffWinder** [comment]
Okay, I think I see what happened. When I wanted to log `setTimeout` in socket.js, VS Code added 
`const { setTimeout } = require('timers');` for me. 
This makes the error go away. So it looks like when leaving out this import javascript's `setTimeout` is being used, resulting in the error?

**Comment by darrachequesne** [comment]
Were you able to find a solution? Is there something we can fix on our end?

**Comment by JeffWinder** [comment]
I think it would be best to explicitly import `setTimeout` and `clearTimeout` from Node's timers module, by adding this in  lib/socket.ts:
`import { setTimeout, clearTimeout } from "timers";`
That would make sure compilers don't mistaken those functions for javascript timers, of which setTimeout doesn't have a `refresh` function. Hence the error in my scenario.

I can also make a PR for that tomorrow if you like.

**Comment by JeffWinder** [comment]
Here's the PR: https://github.com/socketio/engine.io/pull/632

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io/pull/632.
