### ISSUE TITLE
uWebSocket: allow to specify compression option

### ISSUE THREAD

**Issue by yosiat** [socketio/engine.io#633]
Hi,

I am so excited about uWebSocket support and I want to roll it out, but I saw uWebSocket have support for multiple compression options - SHARED_COMPRESSOR, DEDICATED, etc.. and I would like to tune it for my application use-case.

https://unetworking.github.io/uWebSockets.js/generated/interfaces/WebSocketBehavior.html#compression

Is is possible to expose from socket.io to pass an option to engine.io to allow configuration compression option here -
https://github.com/socketio/engine.io/blob/master/lib/userver.ts#L50

I can implement it, but not sure what's the best way (to have this as "generic" option and not transport specific)

**Comment by yosiat** [comment]
In addition it will be nice to pass `drain` function so I can create metric on buffered amount to see if that requires tuning

**Comment by darrachequesne** [comment]
That's a great idea! Would you have time to open a pull request?

**Comment by yosiat** [comment]
@darrachequesne yes, but since this uwebsocket specific option how you want to model it? is it make sense to add uWebSocket configuration under `ServerOption` type?

**Comment by darrachequesne** [comment]
@yosiat it should work with an union type:

```ts
public attach(app /* : TemplatedApp */, options: AttachOptions & { compression?: number } = {}) {
    const path = (options.path || "/engine.io").replace(/\/$/, "") + "/";
    // ...
}
```

What do you think?

**Comment by yosiat** [comment]
@darrachequesne sounds good and then we will pass this union here as well - https://github.com/socketio/socket.io/blob/master/lib/index.ts#L353 ?

**Comment by darrachequesne** [comment]
Yes 👍

**Comment by darrachequesne** [comment]
This has been implemented in https://github.com/socketio/engine.io/commit/49bb7cf66518d4b49baf883a16ee1fe1ed8aed28, and included in `engine.io@6.1.2`. Thanks!
