### ISSUE TITLE
transports-uws/polling.js: TypeError: res.onData is not a function

### ISSUE THREAD

**Issue by bogdankatishev** [socketio/engine.io#637]
Hello,

When testing uws on our socket server, we found a issue. I have configured a socket-io client to only do polling as transport, but when sending the request from socket-io client to the socket-io server, i found this in my socket server console:
```
node_modules/engine.io/build/transports-uws/polling.js:133
        res.onData((chunk, isLast) => {
            ^
TypeError: res.onData is not a function
```

And then it crashes the node server.

**Comment by darrachequesne** [comment]
Hi! That sounds really weird. The source code is here:

https://github.com/socketio/engine.io/blob/49bb7cf66518d4b49baf883a16ee1fe1ed8aed28/lib/transports-uws/polling.ts#L166-L180

The question is: how can `res.onData()` fail whereas `res.onAborted()` above succeeds?

Are you able to reproduce? I wasn't with the following code:

*Server*

```js
const { App } = require("uWebSockets.js");
const { Server } = require("socket.io");

const app = new App();
const io = new Server();

io.attachApp(app);

io.on("connection", (socket) => {
  setInterval(() => {
    socket.emit("wut", () => {
      console.log("acked!")
    })
  }, 1000);

  socket.on("woot", (cb) => {
    cb();
  });
});

app.listen(4000, (token) => {
  if (!token) {
    console.warn("port already in use");
  }
});
```

*Client*

```js
const io = require("socket.io-client");

const socket = io("http://localhost:4000", {
  transports: ["polling"]
});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

setInterval(() => {
  socket.emit("woot", () => {
    console.log("acked!")
  })
}, 1000)

socket.on("wut", (cb) => {
  cb();
});

```

**Comment by darrachequesne** [comment]
OK, so I've finally able to reproduce. It should be fixed by https://github.com/socketio/engine.io/commit/45112a30d1af4cc25b21a5d658a748583cb64ed4, included in `engine.io-client@6.1.2`.

Thanks for raising the issue! Please reopen if needed.
