### ISSUE TITLE
Bad package reference causes error on upstream builds

### ISSUE THREAD

**Issue by jasonkenneth** [socketio/engine.io#639]
We're keeping our dependencies up to date on an Angular 12 / nestjs / nrwl monorepo application. When I upgraded to the latest versions of socket.io, I get a build error from within node_modules.

```shell
Error: node_modules/engine.io/build/transport.d.ts:4:10 - error TS2305: Module '"engine.io-parser"' has no exported member 'Packet'.

4 import { Packet } from "engine.io-parser";
           ~~~~~~
```

It turns out it's because the vLatest of engine.io actually requires at least `engine.io-parser` v5.0.3, but the reference only pulls `~5.0.0`. If I install engine.io-parser directly in my app to 5.0.3, the build error disappears.

https://github.com/socketio/engine.io/blob/90fb0a99acd44fe424f14516d9575b09a0cfc582/package.json#L42

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io/commit/1bc5b1a2fde06692194cab037c88e55b0934ed6b, included in `engine.io@6.1.3`.
