### ISSUE TITLE
error TS2305: Module '"engine.io-parser"' has no exported member 'Packet'.

### ISSUE THREAD

**Issue by jojomatik** [socketio/engine.io#640]
**Describe the bug**
An error is thrown while running `tsc` in my typescript project using `engine.io` on version `v6.1.2`.

```
Run cd backend && tsc
  cd backend && tsc
  shell: /usr/bin/bash -e {0}
Error: ../node_modules/engine.io/build/transport.d.ts(4,10): error TS2305: Module '"engine.io-parser"' has no exported member 'Packet'.
Error: Process completed with exit code 2.
```

**To Reproduce**

Please fill the following code example:

*not applicable*

Engine.IO server version: `v6.1.2`

**Expected behavior**
`tsc` runs without any issues as it does on version `v6.1.1`

**Platform:**
 - Software: tsc
 - OS: ubuntu

**Additional context**

The logs of the workflows can be found here https://github.com/jojomatik/blockcluster/runs/4993540002 (`v6.1.2`) and here https://github.com/jojomatik/blockcluster/actions/runs/1767019400 (`v6.1.1`). The respective commits are linked from within the workflows.

I'm sorry for not filling in the fields of the template correctly, but they didn't seem applicable to this bug report. I might end up adding additional information tomorrow, as I dig deeper into the topic.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io/commit/1bc5b1a2fde06692194cab037c88e55b0934ed6b, included in `engine.io@6.1.3`.
