### ISSUE TITLE
[TS] socket.id is private and there is no public getter

### ISSUE THREAD

**Issue by SonahtQ** [socketio/engine.io#644]
**Describe the bug**
Recently engine.io got whole new typescript code, but there are places that need for fixes.
One of it is private field `id` in `Socket` class. Getting and `id` of `Socket` is one of core mechanism that people use in theirs projects. Now there is no way for getting an `id` of `Socket` due to it's private accessor.

Engine.IO server version: `6.2.0`

**Solution**
`id` field in `Socket` class is set to be readonly so it should be 100% safe to switch it from being private to being public.
Other way for fixing it can be for example adding public getter method to `Socket` class.

**Comment by darrachequesne** [comment]
I don't think this is a good idea, as it might lead users to think that the id can be safely shared with others. What do you think?

I added a note in https://github.com/socketio/engine.io/commit/3d28229cf0ce0d017a0045f41736327dee0b7221.

Please reopen if needed.
