### ISSUE TITLE
TypeError: Cannot destructure property 'Server' of '_engineIo.default'

### ISSUE THREAD

**Issue by richardeschloss** [socketio/engine.io#657]
**Describe the bug**

In a library I've written, when I attempt to import from "socket.io", I encounter an error "TypeError: Cannot destructure property 'Server' of '_engineIo.default'. I am able to fix this by updating the first line in [wrapper.mjs](https://github.com/socketio/engine.io/blob/917d1d29e13f2e8f523c3738f6413f67b587aebe/wrapper.mjs#L1):

```js
import * as lib from "./build/engine.io.js"; // instead of: import lib from "./build/engine.io.js", which assumes a default export
```
Please let me know if you'd be open to the proposed change. I can submit the PR if you'd like.

Linked issue: https://github.com/richardeschloss/nuxt-socket-io/issues/278

**Comment by darrachequesne** [comment]
Hi! Unfortunately I'm not able to reproduce the issue, either with TS/plain JS or CJS/ESM imports.

Could it be linked to https://github.com/nuxt/framework/issues/7206?

Note: the current wrapper matches the documentation there: https://nodejs.org/docs/latest-v16.x/api/packages.html#approach-1-use-an-es-module-wrapper

**Comment by Thy3634** [comment]
I got this too, and this is the reason.

source code:
```js
// wrapper.mjs
import lib from "./build/engine.io.js";

export const { Server, Socket, Transport, transports, listen, attach, parser, protocol } = lib;
```

But './build/engine.io.js' never export a 'default'. So I just change the first line into: `import * as lib from "./build/engine.io.js";`

It works.

**Comment by console0811** [comment]
I opened an issue to nuxt 3, any workaround on this?

**Comment by u-hafner** [comment]
I have the same problem with nuxt stable version. Is there any way currently to work around this problem?

**Comment by console0811** [comment]
> 

I did a research, so far I've seen none.
