### ISSUE TITLE
Possible error in websocket code

### ISSUE THREAD

**Issue by billouboq** [socketio/engine.io#671]
Was wondering, isn't it supposed to be the opposite in this code ?

```ts
const len =
            "string" === typeof data ? Buffer.byteLength(data) : data.length;
```
If it's a string we need to use .length otherwise it's a buffer and so we use Buffer.byteLength

----
In file : lib/transports/websocket.ts
Line: 88
https://github.com/socketio/engine.io/blob/535b068670848f6a3193528582484826a858d680/lib/transports/websocket.ts#L88

**Comment by darrachequesne** [comment]
Hi! In both cases, we want to compute the number of bytes of the payload, so it's OK, isn't it?

**Comment by billouboq** [comment]
Wasn't sure but if it's okay we can close this ticket
