### ISSUE TITLE
clientsCount property of server... why need to keep this private,

### ISSUE THREAD

**Issue by devashishg** [socketio/engine.io#672]
https://github.com/socketio/engine.io/blob/7033c0ed278705b569afef0bfe470c1937d1ec38/lib/server.ts#L147

Prior to migration it was accessible form server's engine property, but now this is made private and though the count is being updated but never getting used.
Can we get back to keeping this public property of Abstract class `BaseServer`.

**Comment by darrachequesne** [comment]
Hi! You are right, the `clientsCount` has been made private during the migration to TypeScript, but this is not really needed. Let's change this :+1:
