### ISSUE TITLE
Node.js versions below 10.2 are not compatible with the latest version 6.5.1.

### ISSUE THREAD

**Issue by guohaoyun** [socketio/engine.io#686]
In version 6.4.1, in the 'onPacket' method of '[engine.io/build/socket.js](http://engine.io/build/socket.js)', the 'pong' event does not execute 'this.pingIntervalTimer.refresh()', while in the latest version 6.5.1, it does execute. The 'refresh' method was introduced in Node.js v10.2, so it throws an exception when executed in lower versions, resulting in 'this.pingIntervalTimer.refresh() is not a function' error and causing the service to crash. Please document this situation to prevent errors for users using lower versions of Node.js.

**Comment by darrachequesne** [comment]
Hi! I have updated the range of supported versions: https://github.com/socketio/engine.io/commit/7dd1350bf93542282eba96ed6f5162dc249a7e65

Thanks for the heads-up!
