### ISSUE TITLE
WebTransport If the length of the data block exceeds maxDatagramSize, the server will be unable to receive the complete message (the client will not send the complete message).

### ISSUE THREAD

**Issue by zishang520** [socketio/engine.io#687]
**Is your feature request related to a problem? Please describe.**
Hello, I have a question about WebTransport. If the length of the data block exceeds [maxDatagramSize](https://w3c.github.io/webtransport/#dom-webtransportdatagramduplexstream-maxdatagramsize), the server will be unable to receive the complete message (the client will not send the complete message). From my review of the existing server/client code in the main branch, I haven't found any data block splitting handling.

**Describe the solution you'd like**
- For data packets that exceed [maxDatagramSize](https://w3c.github.io/webtransport/#dom-webtransportdatagramduplexstream-maxdatagramsize), add relevant message headers (similar to the existing binary data handling) to indicate that the next few data blocks represent one packet message, and it is also important to specify the length of the data packets explicitly.
- Ideally, packet reordering issues should not occur, right? If there are such issues, it's essential to consider the order of the packets after splitting.
- Discard data packets that exceed a specified size (e.g., use the existing maxHttpBufferSize).

**Describe alternatives you've considered**
I have considered that the server sends a message to specify the size of the data packet for transmission. I think it seems unreliable, and the degree of support of different browsers is not consistent.

**Additional context**
None for now, testing with Firefox browser can send data longer than maxDatagramSize, but the data received by the server seems to be unstable, and some data will be lost

**Comment by darrachequesne** [comment]
I'm digging into this.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io/commit/a306db09e8ddb367c7d62f45fec920f979580b7c, included in version [6.5.2](https://github.com/socketio/engine.io/releases/tag/6.5.2). Please reopen if needed.
