### ISSUE TITLE
Add support for Node.js built-in WebSocket?

### ISSUE THREAD

**Issue by thernstig** [socketio/engine.io#691]
**Is your feature request related to a problem? Please describe.**
I would like to decrease number of dependencies as it is a maintenance burden.

**Describe the solution you'd like**
Node.js 21 includes native WebSocket support under the `--experimental-websocket`. It would be nice if there was some kind of opt-in behavior to use it.

**Describe alternatives you've considered**
Keep using the `ws` socket.io dependency.

**Additional context**
I am not sure if this is even feasible. You'd need to install the `ws` package anyway for those running on Node <21. So it is possible this issue shall be closed immediately with "no action".

**Comment by darrachequesne** [comment]
Thanks for the heads-up! We could indeed use the new WebSocket client, though I'm not sure how we could conditionally import it and support both Node.js < 21 and Node.js > 21.

Source: https://github.com/socketio/engine.io-client/blob/main/lib/transports/websocket-constructor.ts

**Comment by thernstig** [comment]
@darrachequesne maybe a bigger problem is if you support other platforms (Deno?) then it might be even more problematic?

Publishing different npm packages in your build pipeline would be one way, but maybe that is not wanted.

**Comment by thernstig** [comment]
The ws client is offical (noy under a flag) since the main release of Node.js 22.

**Comment by darrachequesne** [comment]
The Engine.IO client now supports providing a list of transport implementations:

```js
import { Socket, XHR, WebSocket } from "engine.io-client";

const socket = new Socket({
  transports: [XHR, WebSocket]
});
```

So you can now use `transports: [NodeXHR, WebSocket]` or `[Fetch, WebSocket]` with the Node.js client, which will use the built-in WebSocket object.

Included in version [6.6.0](https://github.com/socketio/engine.io-client/releases/tag/6.6.0).

**Comment by thernstig** [comment]
@darrachequesne the main problem most have would be that they want smaller bundles i.e. not having this installed:

https://github.com/socketio/engine.io/blob/791aa58f4c0a003335a945fdd704cb910bd35970/package.json#L44

But that might be neigh impossible to solve for you, unless you publish separate packages, which I assume you do not want.

**Comment by darrachequesne** [comment]
@thernstig yes, we could indeed move the Node.js-specific transport implementations in their own package (along with `xmlhttprequest-ssl` and `ws`), but that would add some additional complexity for the end users, so I'm not sure about this change.

**Comment by thernstig** [comment]
@darrachequesne understandable. Just to list them, the benefits to not have to include `ws` for those using the built-in Node.js WebSocket client, is that you get smaller downloads, but more importantly, less security vulnerabilities that can happen in packages. Which can be quite a churn at times. Let's see if someone else opens a similar request or so in the future.
