### ISSUE TITLE
`websocket`: `send` callbacks are not all called if multiple messages are sent rapidly

### ISSUE THREAD

**Issue by jonathanperret** [socketio/engine.io#698]
**Describe the bug**

When using the `websocket` transport, if `socket.send()` is called multiple times in the same tick with a callback provided, some of the callbacks may not be called even though the messages were sent.

**To Reproduce**

Engine.IO server version: `6.5.4`

*Server*

```js
const engine = require("engine.io");
const server = engine.listen(3000, { transports: ["websocket"] });

server.on("connection", (socket) => {
  console.log("connection");

  socket.send("1", ()=>console.log("callback 1 called"));
  socket.send("2", ()=>console.log("callback 2 called"));
  socket.send("3", ()=>console.log("callback 3 called"));
  socket.send("4", ()=>console.log("callback 4 called"));

  socket.on("close", () => {
    console.log("close");
  });
});
```

Engine.IO client version: `6.5.0`

*Client*

```js
const socket = new (require("engine.io-client").Socket)("ws://localhost:3000", { transports:["websocket"] });

socket.on("open", () => {
  console.log("open");

  socket.on("message", (data) => {
    console.log("data", data);
  });

  socket.on("close", () => {
    console.log("close");
  });
});
```

**Expected behavior**

The server above should log:

```
connection
callback 1 called
callback 2 called
callback 3 called
callback 4 called
```

Instead it logs:

```
connection
callback 1 called
callback 2 called
```

It does log `callback 3 called` after about 25 seconds, and `callback 4 called` 25 seconds later — enabling debug logs shows that `ping` packets are triggering those late callbacks.

The client logs that the messages are all received immediately.

**Platform:**
 - Device: M1 MacBook Pro
 - OS: macOS Sonoma 14.2

**Additional context**

There is an existing [test](https://github.com/socketio/engine.io/blob/0efa04b5841816d18b0c6ebf7c5f592f8382978a/test/server.js#L2762) that is supposed to check this scenario. However it does not expose this bug, because it does not specify a transport and defaults to `polling`, which also makes it redundant with the [next test](https://github.com/socketio/engine.io/blob/0efa04b5841816d18b0c6ebf7c5f592f8382978a/test/server.js#L2790). That first test also only sends two messages, when the test program above shows that only the third and further callbacks are delayed.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io/commit/fc21c4a05f9d50d7efd62aa7a937fadce385e919, included in version [6.6.0](https://github.com/socketio/engine.io/releases/tag/6.6.0). Thanks!
